/*
 Highcharts 4.0.4 JS v/Highstock 2.0.4 (2014-09-02)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(){function y(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function D(){var a,b=arguments,c,d={},e=function(a,b){var c,d;"object"!==typeof a&&(a={});for(d in b)b.hasOwnProperty(d)&&((c=b[d])&&"object"===typeof c&&"[object Array]"!==Object.prototype.toString.call(c)&&"renderTo"!==d&&"number"!==typeof c.nodeType?a[d]=e(a[d]||{},c):a[d]=b[d]);return a};!0===b[0]&&(d=b[1],b=Array.prototype.slice.call(b,2));c=b.length;for(a=0;a<c;a++)d=e(d,b[a]);return d}function B(a,b){return parseInt(a,
b||10)}function ea(a){return"string"===typeof a}function Z(a){return a&&"object"===typeof a}function la(a){return"[object Array]"===Object.prototype.toString.call(a)}function $(a){return"number"===typeof a}function Ha(a){return J.log(a)/J.LN10}function aa(a){return J.pow(10,a)}function ma(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function t(a){return a!==v&&null!==a}function C(a,b,c){var d,e;if(ea(b))t(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(t(b)&&
Z(b))for(d in b)a.setAttribute(d,b[d]);return e}function na(a){return la(a)?a:[a]}function l(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],c!==v&&null!==c)return c}function O(a,b){fa&&!P&&b&&b.opacity!==v&&(b.filter="alpha(opacity="+100*b.opacity+")");y(a.style,b)}function oa(a,b,c,d,e){a=A.createElement(a);b&&y(a,b);e&&O(a,{padding:0,border:"none",margin:0});c&&O(a,c);d&&d.appendChild(a);return a}function Ta(a,b){var c=function(){return v};c.prototype=new a;y(c.prototype,b);return c}
function ba(a,b,c,d){var e=V.numberFormat,f=I.lang,g=+a||0,h=-1===b?(g.toString().split(".")[1]||"").length:isNaN(b=W(b))?2:b,k=void 0===c?f.decimalPoint:c,f=void 0===d?f.thousandsSep:d,m=0>g?"-":"",q=String(B(g=W(g).toFixed(h))),p=3<q.length?q.length%3:0;return e!==ba?e(a,b,c,d):m+(p?q.substr(0,p)+f:"")+q.substr(p).replace(/(\d{3})(?=\d)/g,"$1"+f)+(h?k+W(g-q).toFixed(h).slice(2):"")}function ga(a,b){return Array((b||2)+1-String(a).length).join(0)+a}function Ia(a,b,c){var d=a[b];a[b]=function(){var a=
Array.prototype.slice.call(arguments);a.unshift(d);return c.apply(this,a)}}function ua(a,b){for(var c="{",d=!1,e,f,g,h,k,m=[];-1!==(c=a.indexOf(c));){e=a.slice(0,c);if(d){f=e.split(":");g=f.shift().split(".");k=g.length;e=b;for(h=0;h<k;h++)e=e[g[h]];f.length&&(f=f.join(":"),g=/\.([0-9])/,h=I.lang,k=void 0,/f$/.test(f)?(k=(k=f.match(g))?k[1]:-1,null!==e&&(e=ba(e,k,h.decimalPoint,-1<f.indexOf(",")?h.thousandsSep:""))):e=va(f,e))}m.push(e);a=a.slice(c+1);c=(d=!d)?"}":"{"}m.push(a);return m.join("")}
function lb(a,b,c,d){var e;c=l(c,1);e=a/c;b||(b=[1,2,2.5,5,10],!1===d&&(1===c?b=[1,2,5,10]:.1>=c&&(b=[1/c])));for(d=0;d<b.length&&!(a=b[d],e<=(b[d]+(b[d+1]||b[d]))/2);d++);return a*c}function Ja(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function wa(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function pa(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function xa(a,b){for(var c in a)a[c]&&
a[c]!==b&&a[c].destroy&&a[c].destroy(),delete a[c]}function ya(a){za||(za=oa("div"));a&&za.appendChild(a);za.innerHTML=""}function X(a){return parseFloat(a.toPrecision(14))}function Ua(){var a=I.global.useUTC,b=a?"getUTC":"get";Va=I.global.Date||window.Date;Wa=6E4*(a&&I.global.timezoneOffset||0);Xa=b+"Minutes";Ya=b+"Hours";Za=b+"Day";$a=b+"Date";ab=b+"Month";bb=b+"FullYear"}function K(){}function ia(a,b,c,d){this.axis=a;this.pos=b;this.type=c||"";this.isNew=!0;c||d||this.addLabel()}function Aa(){this.init.apply(this,
arguments)}function Ka(){this.init.apply(this,arguments)}var v,A=document,w=window,J=Math,z=J.round,Q=J.floor,ja=J.ceil,u=J.max,T=J.min,W=J.abs,qa=J.cos,Ba=J.sin,cb=J.PI,db=2*cb/360,ha=navigator.userAgent,mb=w.opera,fa=/msie/i.test(ha)&&!mb,nb=/AppleWebKit/.test(ha),Ca=/Firefox/.test(ha),eb=/(Mobile|Android|Windows Phone)/.test(ha),P=!!A.createElementNS&&!!A.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,ob=Ca&&4>parseInt(ha.split("Firefox/")[1],10),Y=!P&&!fa&&!!A.createElement("canvas").getContext,
fb={},La=0,za,I,va,R,Ma,N,ca=[],gb=0,pb=/^[0-9]+$/,Va,Wa,Xa,Ya,Za,$a,ab,bb,ra={},V;w.Highcharts?N(16,!0):V=w.Highcharts={};va=function(a,b,c){if(!t(b)||isNaN(b))return"Invalid date";a=l(a,"%Y-%m-%d %H:%M:%S");var d=new Va(b-Wa),e,f=d[Ya](),g=d[Za](),h=d[$a](),k=d[ab](),m=d[bb](),q=I.lang,p=q.weekdays,d=y({a:p[g].substr(0,3),A:p[g],d:ga(h),e:h,b:q.shortMonths[k],B:q.months[k],m:ga(k+1),y:m.toString().substr(2,2),Y:m,H:ga(f),I:ga(f%12||12),l:f%12||12,M:ga(d[Xa]()),p:12>f?"AM":"PM",P:12>f?"am":"pm",
S:ga(d.getSeconds()),L:ga(z(b%1E3),3)},V.dateFormats);for(e in d)for(;-1!==a.indexOf("%"+e);)a=a.replace("%"+e,"function"===typeof d[e]?d[e](b):d[e]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};N=function(a,b){var c="Highcharts error #"+a+": www.highcharts.com/errors/"+a;if(b)throw c;w.console&&console.log(c)};Ma={init:function(a,b,c){b=b||"";var d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g;b=b.split(" ");c=[].concat(c);var h,k,m=function(a){for(g=a.length;g--;)"M"===a[g]&&a.splice(g+1,0,a[g+1],
a[g+2],a[g+1],a[g+2])};e&&(m(b),m(c));a.isArea&&(h=b.splice(b.length-6,6),k=c.splice(c.length-6,6));if(d<=c.length/f&&b.length===c.length)for(;d--;)c=[].concat(c).splice(0,f).concat(c);a.shift=0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(k));return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-
d)+d;else e=b;return e}};(function(a){w.HighchartsAdapter=w.HighchartsAdapter||a&&{init:function(b){var c=a.fx;a.extend(a.easing,{easeOutQuad:function(a,b,c,g,h){return-g*(b/=h)*(b-2)+c}});a.each(["cur","_default","width","height","opacity"],function(b,e){var f=c.step,g;"cur"===e?f=c.prototype:"_default"===e&&a.Tween&&(f=a.Tween.propHooks[e],e="set");(g=f[e])&&(f[e]=function(a){var c;a=b?a:this;if("align"!==a.prop)return c=a.elem,c.attr?c.attr(a.prop,"cur"===e?v:a.now):g.apply(this,arguments)})});
Ia(a.cssHooks.opacity,"get",function(a,b,c){return b.attr?b.opacity||0:a.call(this,b,c)});this.addAnimSetter("d",function(a){var c=a.elem,f;a.started||(f=b.init(c,c.d,c.toD),a.start=f[0],a.end=f[1],a.started=!0);c.attr("d",b.step(a.start,a.end,a.pos,c.toD))});this.each=Array.prototype.forEach?function(a,b){return Array.prototype.forEach.call(a,b)}:function(a,b){var c,g=a.length;for(c=0;c<g;c++)if(!1===b.call(a[c],a[c],c,a))return c};a.fn.highcharts=function(){var a="Chart",b=arguments,c,g;this[0]&&
(ea(b[0])&&(a=b[0],b=Array.prototype.slice.call(b,1)),c=b[0],c!==v&&(c.chart=c.chart||{},c.chart.renderTo=this[0],new V[a](c,b[1]),g=this),c===v&&(g=ca[C(this[0],"data-highcharts-chart")]));return g}},addAnimSetter:function(b,c){a.Tween?a.Tween.propHooks[b]={set:c}:a.fx.step[b]=c},getScript:a.getScript,inArray:a.inArray,adapterRun:function(b,c){return a(b)[c]()},grep:a.grep,map:function(a,c){for(var d=[],e=0,f=a.length;e<f;e++)d[e]=c.call(a[e],a[e],e,a);return d},offset:function(b){return a(b).offset()},
addEvent:function(b,c,d){a(b).bind(c,d)},removeEvent:function(b,c,d){var e=A.removeEventListener?"removeEventListener":"detachEvent";A[e]&&b&&!b[e]&&(b[e]=function(){});a(b).unbind(c,d)},fireEvent:function(b,c,d,e){var f=a.Event(c),g="detached"+c,h;!fa&&d&&(delete d.layerX,delete d.layerY,delete d.returnValue);y(f,d);b[c]&&(b[g]=b[c],b[c]=null);a.each(["preventDefault","stopPropagation"],function(a,b){var c=f[b];f[b]=function(){try{c.call(f)}catch(a){"preventDefault"===b&&(h=!0)}}});a(b).trigger(f);
b[g]&&(b[c]=b[g],b[g]=null);!e||f.isDefaultPrevented()||h||e(f)},washMouseEvent:function(a){var c=a.originalEvent||a;c.pageX===v&&(c.pageX=a.pageX,c.pageY=a.pageY);return c},animate:function(b,c,d){var e=a(b);b.style||(b.style={});c.d&&(b.toD=c.d,c.d=1);e.stop();c.opacity!==v&&b.attr&&(c.opacity+="px");b.hasAnim=1;e.animate(c,d)},stop:function(b){b.hasAnim&&a(b).stop()}}})(w.jQuery);var Da=w.HighchartsAdapter,U=Da||{};Da&&Da.init.call(Da,Ma);var Ea=U.adapterRun,qb=U.inArray,s=U.each,hb=U.grep,ib=
U.map,L=U.addEvent,S=U.removeEvent,M=U.fireEvent,jb=U.animate,Na=U.stop,Oa={enabled:!0,x:0,y:15,style:{color:"#606060",cursor:"default",fontSize:"11px"}};I={colors:"#7cb5ec #434348 #90ed7d #f7a35c #8085e9 #f15c80 #e4d354 #8085e8 #8d4653 #91e8e1".split(" "),symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:!0,canvasToolsURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/modules/canvas-tools.js",VMLRadialGradientURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/gfx/vml-radial-gradient.png"},chart:{borderColor:"#4572A7",borderRadius:0,defaultSeriesType:"line",
ignoreHiddenSeries:!0,spacing:[10,10,15,10],backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0",resetZoomButton:{theme:{zIndex:20},position:{align:"right",x:-10,y:10}}},title:{text:"Chart title",align:"center",margin:15,style:{color:"#333333",fontSize:"18px"}},subtitle:{text:"",align:"center",style:{color:"#555555"}},plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},events:{},lineWidth:2,marker:{lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{enabled:!0,lineWidthPlus:1,
radiusPlus:2},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:D(Oa,{align:"center",enabled:!1,formatter:function(){return null===this.y?"":ba(this.y,-1)},verticalAlign:"bottom",y:0}),cropThreshold:300,pointRange:0,states:{hover:{lineWidthPlus:1,marker:{},halo:{size:10,opacity:.25}},select:{marker:{}}},stickyTracking:!0,turboThreshold:1E3}},labels:{style:{position:"absolute",color:"#3E576F"}},legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},
borderColor:"#909090",borderRadius:0,navigation:{activeColor:"#274b6d",inactiveColor:"#CCC"},shadow:!1,itemStyle:{color:"#333333",fontSize:"12px",fontWeight:"bold"},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"white",opacity:.5,
textAlign:"center"}},tooltip:{enabled:!0,animation:P,backgroundColor:"rgba(249, 249, 249, .85)",borderWidth:1,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',
shadow:!0,snap:eb?25:10,style:{color:"#333333",cursor:"default",fontSize:"12px",padding:"8px",whiteSpace:"nowrap"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",fontSize:"9px"}}};var Pa=I.plotOptions;Ua();var rb=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,sb=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/,tb=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,
sa=function(a){var b=[],c,d;(function(a){a&&a.stops?d=ib(a.stops,function(a){return sa(a[1])}):(c=rb.exec(a))?b=[B(c[1]),B(c[2]),B(c[3]),parseFloat(c[4],10)]:(c=sb.exec(a))?b=[B(c[1],16),B(c[2],16),B(c[3],16),1]:(c=tb.exec(a))&&(b=[B(c[1]),B(c[2]),B(c[3]),1])})(a);return{get:function(c){var f;d?(f=D(a),f.stops=[].concat(f.stops),s(d,function(a,b){f.stops[b]=[f.stops[b][0],a.get(c)]})):f=b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":a;return f},brighten:function(a){if(d)s(d,
function(b){b.brighten(a)});else if($(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=B(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},rgba:b,setOpacity:function(a){b[3]=a;return this}}};K.prototype={opacity:1,textProps:"fontSize fontWeight fontFamily color lineHeight width textDecoration textShadow HcTextStroke".split(" "),init:function(a,b){this.element="span"===b?oa(b):A.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b,c){b=l(b,R,!0);Na(this);b?(b=D(b,{}),
c&&(b.complete=c),jb(this,a,b)):(this.attr(a),c&&c());return this},colorGradient:function(a,b,c){var d=this.renderer,e,f,g,h,k,m,q,p,r,n,l=[];a.linearGradient?f="linearGradient":a.radialGradient&&(f="radialGradient");if(f){g=a[f];h=d.gradients;m=a.stops;r=c.radialReference;la(g)&&(a[f]=g={x1:g[0],y1:g[1],x2:g[2],y2:g[3],gradientUnits:"userSpaceOnUse"});"radialGradient"===f&&r&&!t(g.gradientUnits)&&(g=D(g,{cx:r[0]-r[2]/2+g.cx*r[2],cy:r[1]-r[2]/2+g.cy*r[2],r:g.r*r[2],gradientUnits:"userSpaceOnUse"}));
for(n in g)"id"!==n&&l.push(n,g[n]);for(n in m)l.push(m[n]);l=l.join(",");h[l]?a=h[l].attr("id"):(g.id=a="highcharts-"+La++,h[l]=k=d.createElement(f).attr(g).add(d.defs),k.stops=[],s(m,function(a){0===a[1].indexOf("rgba")?(e=sa(a[1]),q=e.get("rgb"),p=e.get("a")):(q=a[1],p=1);a=d.createElement("stop").attr({offset:a[0],"stop-color":q,"stop-opacity":p}).add(k);k.stops.push(a)}));c.setAttribute(b,"url("+d.url+"#"+a+")")}},attr:function(a,b){var c,d,e=this.element,f,g=this,h;"string"===typeof a&&b!==
v&&(c=a,a={},a[c]=b);if("string"===typeof a)g=(this[a+"Getter"]||this._defaultGetter).call(this,a,e);else{for(c in a)d=a[c],h=!1,this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(c)&&(f||(this.symbolAttr(a),f=!0),h=!0),!this.rotation||"x"!==c&&"y"!==c||(this.doTransform=!0),h||(this[c+"Setter"]||this._defaultSetter).call(this,d,c,e),this.shadows&&/^(width|height|visibility|x|y|d|transform|cx|cy|r)$/.test(c)&&this.updateShadows(c,d);this.doTransform&&(this.updateTransform(),
this.doTransform=!1)}return g},updateShadows:function(a,b){for(var c=this.shadows,d=c.length;d--;)c[d].setAttribute(a,"height"===a?u(b-(c[d].cutHeight||0),0):"d"===a?this.d:b)},addClass:function(a){var b=this.element,c=C(b,"class")||"";-1===c.indexOf(a)&&C(b,"class",c+" "+a);return this},symbolAttr:function(a){var b=this;s("x y r start end width height innerR anchorX anchorY".split(" "),function(c){b[c]=l(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",
a?"url("+this.renderer.url+"#"+a.id+")":"none")},crisp:function(a){var b,c={},d,e=a.strokeWidth||this.strokeWidth||0;d=z(e)%2/2;a.x=Q(a.x||this.x||0)+d;a.y=Q(a.y||this.y||0)+d;a.width=Q((a.width||this.width||0)-2*d);a.height=Q((a.height||this.height||0)-2*d);a.strokeWidth=e;for(b in a)this[b]!==a[b]&&(this[b]=c[b]=a[b]);return c},css:function(a){var b=this.styles,c={},d=this.element,e,f,g="";e=!b;a&&a.color&&(a.fill=a.color);if(b)for(f in a)a[f]!==b[f]&&(c[f]=a[f],e=!0);if(e){e=this.textWidth=a&&
a.width&&"text"===d.nodeName.toLowerCase()&&B(a.width);b&&(a=y(b,c));this.styles=a;e&&(Y||!P&&this.renderer.forExport)&&delete a.width;if(fa&&!P)O(this.element,a);else{b=function(a,b){return"-"+b.toLowerCase()};for(f in a)g+=f.replace(/([A-Z])/g,b)+":"+a[f]+";";C(d,"style",g)}e&&this.added&&this.renderer.buildText(this)}return this},on:function(a,b){this.element["on"+a]=b;return this},setRadialReference:function(a){this.element.radialReference=a;return this},translate:function(a,b){return this.attr({translateX:a,
translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,d=this.scaleY,e=this.inverted,f=this.rotation,g=this.element;e&&(a+=this.attr("width"),b+=this.attr("height"));a=["translate("+a+","+b+")"];e?a.push("rotate(90) scale(-1,1)"):f&&a.push("rotate("+f+" "+(g.getAttribute("x")||0)+" "+(g.getAttribute("y")||0)+")");(t(c)||t(d))&&a.push("scale("+l(c,1)+" "+l(d,1)+")");a.length&&g.setAttribute("transform",
a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){var d,e,f,g,h={};e=this.renderer;f=e.alignedObjects;if(a){if(this.alignOptions=a,this.alignByTranslate=b,!c||ea(c))this.alignTo=d=c||"renderer",ma(f,this),f.push(this),c=null}else a=this.alignOptions,b=this.alignByTranslate,d=this.alignTo;c=l(c,e[d],e);d=a.align;e=a.verticalAlign;f=(c.x||0)+(a.x||0);g=(c.y||0)+(a.y||0);if("right"===d||"center"===d)f+=(c.width-(a.width||0))/{right:1,center:2}[d];
h[b?"translateX":"x"]=z(f);if("bottom"===e||"middle"===e)g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1);h[b?"translateY":"y"]=z(g);this[this.placed?"animate":"attr"](h);this.placed=!0;this.alignAttr=h;return this},getBBox:function(){var a=this.bBox,b=this.renderer,c,d,e=this.rotation;c=this.element;var f=this.styles,g=e*db;d=this.textStr;var h;if(""===d||pb.test(d))h="num."+d.toString().length+(f?"|"+f.fontSize+"|"+f.fontFamily:"");h&&(a=b.cache[h]);if(!a){if("http://www.w3.org/2000/svg"===
c.namespaceURI||b.forExport){try{a=c.getBBox?y({},c.getBBox()):{width:c.offsetWidth,height:c.offsetHeight}}catch(k){}if(!a||0>a.width)a={width:0,height:0}}else a=this.htmlGetBBox();b.isSVG&&(c=a.width,d=a.height,fa&&f&&"11px"===f.fontSize&&"16.9"===d.toPrecision(3)&&(a.height=d=14),e&&(a.width=W(d*Ba(g))+W(c*qa(g)),a.height=W(d*qa(g))+W(c*Ba(g))));this.bBox=a;h&&(b.cache[h]=a)}return a},show:function(a){a&&"http://www.w3.org/2000/svg"===this.element.namespaceURI?this.element.removeAttribute("visibility"):
this.attr({visibility:a?"inherit":"visible"});return this},hide:function(){return this.attr({visibility:"hidden"})},fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||150,complete:function(){b.attr({y:-9999})}})},add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=this.element,f=this.zIndex,g,h;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);f&&(c.handleZ=!0,f=B(f));if(c.handleZ)for(a=d.childNodes,g=0;g<a.length;g++)if(b=
a[g],c=C(b,"zIndex"),b!==e&&(B(c)>f||!t(f)&&t(c))){d.insertBefore(e,b);h=!0;break}h||d.appendChild(e);this.added=!0;if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=this,b=a.element||{},c=a.shadows,d=a.renderer.isSVG&&"SPAN"===b.nodeName&&a.parentGroup,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=b.point=null;Na(a);a.clipPath&&(a.clipPath=a.clipPath.destroy());if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=
a.stops[f].destroy();a.stops=null}a.safeRemoveChild(b);for(c&&s(c,function(b){a.safeRemoveChild(b)});d&&d.div&&0===d.div.childNodes.length;)b=d.parentGroup,a.safeRemoveChild(d.div),delete d.div,d=b;a.alignTo&&ma(a.renderer.alignedObjects,a);for(e in a)delete a[e];return null},shadow:function(a,b,c){var d=[],e,f,g=this.element,h,k,m,q;if(a){k=l(a.width,3);m=(a.opacity||.15)/k;q=this.parentInverted?"(-1,-1)":"("+l(a.offsetX,1)+", "+l(a.offsetY,1)+")";for(e=1;e<=k;e++)f=g.cloneNode(0),h=2*k+1-2*e,C(f,
{isShadow:"true",stroke:a.color||"black","stroke-opacity":m*e,"stroke-width":h,transform:"translate"+q,fill:"none"}),c&&(C(f,"height",u(C(f,"height")-h,0)),f.cutHeight=h),b?b.element.appendChild(f):g.parentNode.insertBefore(f,g),d.push(f);this.shadows=d}return this},xGetter:function(a){"circle"===this.element.nodeName&&(a={x:"cx",y:"cy"}[a]||a);return this._defaultGetter(a)},_defaultGetter:function(a){a=l(this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));
return a},dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a},dashstyleSetter:function(a){var b;if(a=a&&a.toLowerCase()){a=a.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").split(",");for(b=a.length;b--;)a[b]=B(a[b])*this["stroke-width"];a=a.join(",").replace("NaN",
"none");this.element.setAttribute("stroke-dasharray",a)}},alignSetter:function(a){this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,b,c){this[b]=a;c.setAttribute(b,a)},titleSetter:function(a){var b=this.element.getElementsByTagName("title")[0];b||(b=A.createElementNS("http://www.w3.org/2000/svg","title"),this.element.appendChild(b));b.textContent=l(a,"").replace(/<[^>]*>/g,"")},textSetter:function(a){a!==this.textStr&&(delete this.bBox,
this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,b,c){"string"===typeof a?c.setAttribute(b,a):a&&this.colorGradient(a,b,c)},zIndexSetter:function(a,b,c){c.setAttribute(b,a);this[b]=a},_defaultSetter:function(a,b,c){c.setAttribute(b,a)}};K.prototype.yGetter=K.prototype.xGetter;K.prototype.translateXSetter=K.prototype.translateYSetter=K.prototype.rotationSetter=K.prototype.verticalAlignSetter=K.prototype.scaleXSetter=K.prototype.scaleYSetter=function(a,b){this[b]=a;this.doTransform=
!0};K.prototype["stroke-widthSetter"]=K.prototype.strokeSetter=function(a,b,c){this[b]=a;this.stroke&&this["stroke-width"]?(this.strokeWidth=this["stroke-width"],K.prototype.fillSetter.call(this,this.stroke,"stroke",c),c.setAttribute("stroke-width",this["stroke-width"]),this.hasStroke=!0):"stroke-width"===b&&0===a&&this.hasStroke&&(c.removeAttribute("stroke"),this.hasStroke=!1)};var ta=function(){this.init.apply(this,arguments)};ta.prototype={Element:K,init:function(a,b,c,d,e){var f=location,g;d=
this.createElement("svg").attr({version:"1.1"}).css(this.getStyle(d));g=d.element;a.appendChild(g);-1===a.innerHTML.indexOf("xmlns")&&C(g,"xmlns","http://www.w3.org/2000/svg");this.isSVG=!0;this.box=g;this.boxWrapper=d;this.alignedObjects=[];this.url=(Ca||nb)&&A.getElementsByTagName("base").length?f.href.replace(/#.*?$/,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(A.createTextNode("Created with Highcharts 4.0.4 /Highstock 2.0.4"));this.defs=
this.createElement("defs").add();this.forExport=e;this.gradients={};this.cache={};this.setSize(b,c,!1);var h;Ca&&a.getBoundingClientRect&&(this.subPixelFix=b=function(){O(a,{left:0,top:0});h=a.getBoundingClientRect();O(a,{left:ja(h.left)-h.left+"px",top:ja(h.top)-h.top+"px"})},b(),L(w,"resize",b))},getStyle:function(a){return this.style=y({fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',fontSize:"12px"},a)},isHidden:function(){return!this.boxWrapper.getBBox().width},
destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();xa(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.subPixelFix&&S(w,"resize",this.subPixelFix);return this.alignedObjects=null},createElement:function(a){var b=new this.Element;b.init(this,a);return b},draw:function(){},buildText:function(a){for(var b=a.element,c=this,d=c.forExport,e=l(a.textStr,"").toString(),f=-1!==e.indexOf("<"),g=b.childNodes,h,k,m=C(b,"x"),q=a.styles,p=a.textWidth,
r=q&&q.lineHeight,n=q&&q.HcTextStroke,F=g.length,x=function(a){return r?B(r):c.fontMetrics(/(px|em)$/.test(a&&a.style.fontSize)?a.style.fontSize:q&&q.fontSize||c.style.fontSize||12,a).h};F--;)b.removeChild(g[F]);f||n||-1!==e.indexOf(" ")?(h=/<.*style="([^"]+)".*>/,k=/<.*href="(http[^"]+)".*>/,p&&!a.added&&this.box.appendChild(b),e=f?e.replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,
"</span>").split(/<br.*?>/g):[e],""===e[e.length-1]&&e.pop(),s(e,function(e,f){var g,n=0;e=e.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");g=e.split("|||");s(g,function(e){if(""!==e||1===g.length){var r={},l=A.createElementNS("http://www.w3.org/2000/svg","tspan"),F;h.test(e)&&(F=e.match(h)[1].replace(/(;| |^)color([ :])/,"$1fill$2"),C(l,"style",F));k.test(e)&&!d&&(C(l,"onclick",'location.href="'+e.match(k)[1]+'"'),O(l,{cursor:"pointer"}));e=(e.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,
"<").replace(/&gt;/g,">");if(" "!==e){l.appendChild(A.createTextNode(e));n?r.dx=0:f&&null!==m&&(r.x=m);C(l,r);b.appendChild(l);!n&&f&&(!P&&d&&O(l,{display:"block"}),C(l,"dy",x(l)));if(p){e=e.replace(/([^\^])-/g,"$1- ").split(" ");for(var r=1<g.length||1<e.length&&"nowrap"!==q.whiteSpace,s,H,t=q.HcHeight,E=[],v=x(l),kb=1;r&&(e.length||E.length);)delete a.bBox,s=a.getBBox(),H=s.width,!P&&c.forExport&&(H=c.measureSpanWidth(l.firstChild.data,a.styles)),(s=H>p)&&1!==e.length?(l.removeChild(l.firstChild),
E.unshift(e.pop())):(e=E,E=[],e.length&&(kb++,t&&kb*v>t?(e=["..."],a.attr("title",a.textStr)):(l=A.createElementNS("http://www.w3.org/2000/svg","tspan"),C(l,{dy:v,x:m}),F&&C(l,"style",F),b.appendChild(l))),H>p&&(p=H)),e.length&&l.appendChild(A.createTextNode(e.join(" ").replace(/- /g,"-")))}n++}}})})):b.appendChild(A.createTextNode(e))},button:function(a,b,c,d,e,f,g,h,k){var m=this.label(a,b,c,k,null,null,null,null,"button"),q=0,p,r,n,l,x,s;a={x1:0,y1:0,x2:0,y2:1};e=D({"stroke-width":1,stroke:"#CCCCCC",
fill:{linearGradient:a,stops:[[0,"#FEFEFE"],[1,"#F6F6F6"]]},r:2,padding:5,style:{color:"black"}},e);n=e.style;delete e.style;f=D(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#FFF"],[1,"#ACF"]]}},f);l=f.style;delete f.style;g=D(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#9BD"],[1,"#CDF"]]}},g);x=g.style;delete g.style;h=D(e,{style:{color:"#CCC"}},h);s=h.style;delete h.style;L(m.element,fa?"mouseover":"mouseenter",function(){3!==q&&m.attr(f).css(l)});L(m.element,fa?"mouseout":"mouseleave",
function(){3!==q&&(p=[e,f,g][q],r=[n,l,x][q],m.attr(p).css(r))});m.setState=function(a){(m.state=q=a)?2===a?m.attr(g).css(x):3===a&&m.attr(h).css(s):m.attr(e).css(n)};return m.on("click",function(){3!==q&&d.call(m)}).attr(e).css(y({cursor:"default"},n))},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=z(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=z(a[2])+b%2/2);return a},path:function(a){var b={fill:"none"};la(a)?b.d=a:Z(a)&&y(b,a);return this.createElement("path").attr(b)},circle:function(a,b,c){a=Z(a)?
a:{x:a,y:b,r:c};b=this.createElement("circle");b.xSetter=function(a){this.element.setAttribute("cx",a)};b.ySetter=function(a){this.element.setAttribute("cy",a)};return b.attr(a)},arc:function(a,b,c,d,e,f){Z(a)&&(b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x);a=this.symbol("arc",a||0,b||0,c||0,c||0,{innerR:d||0,start:e||0,end:f||0});a.r=c;return a},rect:function(a,b,c,d,e,f){e=Z(a)?a.r:e;var g=this.createElement("rect");a=Z(a)?a:a===v?{}:{x:a,y:b,width:u(c,0),height:u(d,0)};f!==v&&(a.strokeWidth=
f,a=g.crisp(a));e&&(a.r=e);g.rSetter=function(a){C(this.element,{rx:a,ry:a})};return g.attr(a)},setSize:function(a,b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=b;for(this.boxWrapper[l(c,!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return t(a)?b.attr({"class":"highcharts-"+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:"none"};1<arguments.length&&y(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);
f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,b,c,d,e,f){var g,h=this.symbols[a],h=h&&h(z(b),z(c),d,e,f),k=/^url\((.*?)\)$/,m,q;h?(g=this.path(h),y(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&y(g,f)):k.test(a)&&(q=function(a,b){a.element&&(a.attr({width:b[0],height:b[1]}),a.alignByTranslate||a.translate(z((d-b[0])/2),z((e-b[1])/2)))},m=a.match(k)[1],a=fb[m]||f&&f.width&&f.height&&[f.width,
f.height],g=this.image(m).attr({x:b,y:c}),g.isImg=!0,a?q(g,a):(g.attr({width:0,height:0}),oa("img",{onload:function(){q(g,fb[m]=[this.width,this.height])},src:m})));return g},symbols:{circle:function(a,b,c,d){var e=.166*c;return["M",a+c/2,b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return["M",a,b,"L",a+c,
b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start;c=e.r||c||d;var g=e.end-.001;d=e.innerR;var h=e.open,k=qa(f),m=Ba(f),q=qa(g),g=Ba(g);e=e.end-f<cb?0:1;return["M",a+c*k,b+c*m,"A",c,c,0,e,1,a+c*q,b+c*g,h?"M":"L",a+d*q,b+d*g,"A",d,d,0,e,0,a+d*k,b+d*m,h?"":"Z"]},callout:function(a,b,c,d,e){var f=T(e&&e.r||0,c,d),g=f+6,h=e&&e.anchorX,k=e&&e.anchorY;e=z(e.strokeWidth||0)%2/2;a+=e;b+=e;e=["M",a+f,b,"L",a+c-f,b,"C",
a+c,b,a+c,b,a+c,b+f,"L",a+c,b+d-f,"C",a+c,b+d,a+c,b+d,a+c-f,b+d,"L",a+f,b+d,"C",a,b+d,a,b+d,a,b+d-f,"L",a,b+f,"C",a,b,a,b,a+f,b];h&&h>c&&k>b+g&&k<b+d-g?e.splice(13,3,"L",a+c,k-6,a+c+6,k,a+c,k+6,a+c,b+d-f):h&&0>h&&k>b+g&&k<b+d-g?e.splice(33,3,"L",a,k+6,a-6,k,a,k-6,a,b+f):k&&k>d&&h>a+g&&h<a+c-g?e.splice(23,3,"L",h+6,b+d,h,b+d+6,h-6,b+d,a+f,b+d):k&&0>k&&h>a+g&&h<a+c-g&&e.splice(3,3,"L",h-6,b,h,b-6,h+6,b,c-f,b);return e}},clipRect:function(a,b,c,d){var e="highcharts-"+La++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);
a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},text:function(a,b,c,d){var e=Y||!P&&this.forExport,f={};if(d&&!this.forExport)return this.html(a,b,c);f.x=Math.round(b||0);c&&(f.y=Math.round(c));if(a||0===a)f.text=a;a=this.createElement("text").attr(f);e&&a.css({position:"absolute"});d||(a.xSetter=function(a,b,c){var d=c.getElementsByTagName("tspan"),e,f=c.getAttribute(b),r;for(r=0;r<d.length;r++)e=d[r],e.getAttribute(b)===f&&e.setAttribute(b,a);c.setAttribute(b,a)});return a},fontMetrics:function(a,
b){a=a||this.style.fontSize;b&&w.getComputedStyle&&(b=b.element||b,a=w.getComputedStyle(b,"").fontSize);a=/px/.test(a)?B(a):/em/.test(a)?12*parseFloat(a):12;var c=24>a?a+4:z(1.2*a),d=z(.8*c);return{h:c,b:d,f:a}},label:function(a,b,c,d,e,f,g,h,k){function m(){var a,b;a=l.element.style;E=(void 0===ka||void 0===B||n.styles.textAlign)&&l.textStr&&l.getBBox();n.width=(ka||E.width||0)+2*G+Fa;n.height=(B||E.height||0)+2*G;da=G+r.fontMetrics(a&&a.fontSize,l).b;w&&(x||(a=z(-u*G),b=h?-da:0,n.box=x=d?r.symbol(d,
a,b,n.width,n.height,H):r.rect(a,b,n.width,n.height,0,H["stroke-width"]),x.attr("fill","none").add(n)),x.isImg||x.attr(y({width:z(n.width),height:z(n.height)},H)),H=null)}function q(){var a=n.styles,a=a&&a.textAlign,b=Fa+G*(1-u),c;c=h?0:da;t(ka)&&E&&("center"===a||"right"===a)&&(b+={center:.5,right:1}[a]*(ka-E.width));if(b!==l.x||c!==l.y)l.attr("x",b),c!==v&&l.attr("y",c);l.x=b;l.y=c}function p(a,b){x?x.attr(a,b):H[a]=b}var r=this,n=r.g(k),l=r.text("",0,0,g).attr({zIndex:1}),x,E,u=0,G=3,Fa=0,ka,B,
A,Qa,C=0,H={},da,w;n.onAdd=function(){l.add(n);n.attr({text:a||0===a?a:"",x:b,y:c});x&&t(e)&&n.attr({anchorX:e,anchorY:f})};n.widthSetter=function(a){ka=a};n.heightSetter=function(a){B=a};n.paddingSetter=function(a){t(a)&&a!==G&&(G=a,q())};n.paddingLeftSetter=function(a){t(a)&&a!==Fa&&(Fa=a,q())};n.alignSetter=function(a){u={left:0,center:.5,right:1}[a]};n.textSetter=function(a){a!==v&&l.textSetter(a);m();q()};n["stroke-widthSetter"]=function(a,b){a&&(w=!0);C=a%2/2;p(b,a)};n.strokeSetter=n.fillSetter=
n.rSetter=function(a,b){"fill"===b&&a&&(w=!0);p(b,a)};n.anchorXSetter=function(a,b){e=a;p(b,a+C-A)};n.anchorYSetter=function(a,b){f=a;p(b,a-Qa)};n.xSetter=function(a){n.x=a;u&&(a-=u*((ka||E.width)+G));A=z(a);n.attr("translateX",A)};n.ySetter=function(a){Qa=n.y=z(a);n.attr("translateY",Qa)};var I=n.css;return y(n,{css:function(a){if(a){var b={};a=D(a);s(n.textProps,function(c){a[c]!==v&&(b[c]=a[c],delete a[c])});l.css(b)}return I.call(n,a)},getBBox:function(){return{width:E.width+2*G,height:E.height+
2*G,x:E.x-G,y:E.y-G}},shadow:function(a){x&&x.shadow(a);return n},destroy:function(){S(n.element,"mouseenter");S(n.element,"mouseleave");l&&(l=l.destroy());x&&(x=x.destroy());K.prototype.destroy.call(n);n=r=m=q=p=null}})}};ia.prototype={addLabel:function(){var a=this.axis,b=a.options,c=a.chart,d=a.horiz,e=a.categories,f=a.names,g=this.pos,h=b.labels,k=h.rotation,m=a.tickPositions,d=d&&e&&!h.step&&!h.staggerLines&&!h.rotation&&c.plotWidth/m.length||!d&&(c.margin[3]||.33*c.chartWidth),q=g===m[0],p=
g===m[m.length-1],r,f=e?l(e[g],f[g],g):g,e=this.label,n=m.info;a.isDatetimeAxis&&n&&(r=b.dateTimeLabelFormats[n.higherRanks[g]||n.unitName]);this.isFirst=q;this.isLast=p;b=a.labelFormatter.call({axis:a,chart:c,isFirst:q,isLast:p,dateTimeLabelFormat:r,value:a.isLog?X(aa(f)):f});g=d&&{width:u(1,z(d-2*(h.padding||10)))+"px"};t(e)?e&&e.attr({text:b}).css(g):(r={align:a.labelAlign},$(k)&&(r.rotation=k),d&&h.ellipsis&&(g.HcHeight=a.len/m.length),this.label=e=t(b)&&h.enabled?c.renderer.text(b,0,0,h.useHTML).attr(r).css(y(g,
h.style)).add(a.labelGroup):null,a.tickBaseline=c.renderer.fontMetrics(h.style.fontSize,e).b,k&&2===a.side&&(a.tickBaseline*=qa(k*db)));this.yOffset=e?l(h.y,a.tickBaseline+(2===a.side?8:-(e.getBBox().height/2))):0},getLabelSize:function(){var a=this.label,b=this.axis;return a?a.getBBox()[b.horiz?"height":"width"]:0},getLabelSides:function(){var a=this.label.getBBox(),b=this.axis,c=b.horiz,d=b.options.labels,a=c?a.width:a.height,b=c?d.x-a*{left:0,center:.5,right:1}[b.labelAlign]:0;return[b,c?a+b:a]},
handleOverflow:function(a,b){var c=!0,d=this.axis,e=this.isFirst,f=this.isLast,g=d.horiz?b.x:b.y,h=d.reversed,k=d.tickPositions,m=this.getLabelSides(),q=m[0],m=m[1],p,r,n,l=this.label.line;p=l||0;r=d.labelEdge;n=d.justifyLabels&&(e||f);r[p]===v||g+q>r[p]?r[p]=g+m:n||(c=!1);if(n){p=(r=d.justifyToPlot)?d.pos:0;r=r?p+d.len:d.chart.chartWidth;do a+=e?1:-1,n=d.ticks[k[a]];while(k[a]&&(!n||!n.label||n.label.line!==l));d=n&&n.label.xy&&n.label.xy.x+n.getLabelSides()[e?0:1];e&&!h||f&&h?g+q<p&&(g=p-q,n&&g+
m>d&&(c=!1)):g+m>r&&(g=r-m,n&&g+q<d&&(c=!1));b.x=g}return c},getPosition:function(a,b,c,d){var e=this.axis,f=e.chart,g=d&&f.oldChartHeight||f.chartHeight;return{x:a?e.translate(b+c,null,null,d)+e.transB:e.left+e.offset+(e.opposite?(d&&f.oldChartWidth||f.chartWidth)-e.right-e.left:0),y:a?g-e.bottom+e.offset-(e.opposite?e.height:0):g-e.translate(b+c,null,null,d)-e.transB}},getLabelPosition:function(a,b,c,d,e,f,g,h){var k=this.axis,m=k.transA,q=k.reversed,p=k.staggerLines;a=a+e.x-(f&&d?f*m*(q?-1:1):
0);b=b+this.yOffset-(f&&!d?f*m*(q?1:-1):0);p&&(c.line=g/(h||1)%p,b+=k.labelOffset/p*c.line);return{x:a,y:b}},getMarkPath:function(a,b,c,d,e,f){return f.crispLine(["M",a,b,"L",a+(e?0:-c),b+(e?c:0)],d)},render:function(a,b,c){var d=this.axis,e=d.options,f=d.chart.renderer,g=d.horiz,h=this.type,k=this.label,m=this.pos,q=e.labels,p=this.gridLine,r=h?h+"Grid":"grid",n=h?h+"Tick":"tick",s=e[r+"LineWidth"],x=e[r+"LineColor"],t=e[r+"LineDashStyle"],u=e[n+"Length"],r=e[n+"Width"]||0,G=e[n+"Color"],y=e[n+"Position"],
n=this.mark,z=q.step,B=!0,A=d.tickmarkOffset,w=this.getPosition(g,m,A,b),C=w.x,w=w.y,H=g&&C===d.pos+d.len||!g&&w===d.pos?-1:1;c=l(c,1);this.isActive=!0;if(s&&(m=d.getPlotLinePath(m+A,s*H,b,!0),p===v&&(p={stroke:x,"stroke-width":s},t&&(p.dashstyle=t),h||(p.zIndex=1),b&&(p.opacity=0),this.gridLine=p=s?f.path(m).attr(p).add(d.gridGroup):null),!b&&p&&m))p[this.isNew?"attr":"animate"]({d:m,opacity:c});r&&u&&("inside"===y&&(u=-u),d.opposite&&(u=-u),h=this.getMarkPath(C,w,u,r*H,g,f),n?n.animate({d:h,opacity:c}):
this.mark=f.path(h).attr({stroke:G,"stroke-width":r,opacity:c}).add(d.axisGroup));k&&!isNaN(C)&&(k.xy=w=this.getLabelPosition(C,w,k,g,q,A,a,z),this.isFirst&&!this.isLast&&!l(e.showFirstLabel,1)||this.isLast&&!this.isFirst&&!l(e.showLastLabel,1)?B=!1:d.isRadial||q.step||q.rotation||b||0===c||(B=this.handleOverflow(a,w)),z&&a%z&&(B=!1),B&&!isNaN(w.y)?(w.opacity=c,k[this.isNew?"attr":"animate"](w),this.isNew=!1):k.attr("y",-9999))},destroy:function(){xa(this,this.axis)}};Aa.prototype={defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",
second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,gridLineColor:"#C0C0C0",labels:Oa,lineColor:"#C0D0E0",lineWidth:1,minPadding:.01,maxPadding:.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:!1,tickColor:"#C0D0E0",tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#707070"}},
type:"linear"},defaultYAxisOptions:{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8,y:3},lineWidth:0,maxPadding:.05,minPadding:.05,startOnTick:!0,tickWidth:0,title:{rotation:270,text:"Values"},stackLabels:{enabled:!1,formatter:function(){return ba(this.total,-1)},style:Oa.style}},defaultLeftAxisOptions:{labels:{x:-15,y:null},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15,y:null},title:{rotation:90}},defaultBottomAxisOptions:{labels:{x:0,y:null},title:{rotation:0}},
defaultTopAxisOptions:{labels:{x:0,y:-15},title:{rotation:0}},init:function(a,b){var c=b.isX;this.horiz=a.inverted?!c:c;this.coll=(this.isXAxis=c)?"xAxis":"yAxis";this.opposite=b.opposite;this.side=b.side||(this.horiz?this.opposite?0:2:this.opposite?1:3);this.setOptions(b);var d=this.options,e=d.type;this.labelFormatter=d.labels.formatter||this.defaultLabelFormatter;this.userOptions=b;this.minPixelPadding=0;this.chart=a;this.reversed=d.reversed;this.zoomEnabled=!1!==d.zoomEnabled;this.categories=
d.categories||"category"===e;this.names=[];this.isLog="logarithmic"===e;this.isDatetimeAxis="datetime"===e;this.isLinked=t(d.linkedTo);this.tickmarkOffset=this.categories&&"between"===d.tickmarkPlacement&&1===l(d.tickInterval,1)?.5:0;this.ticks={};this.labelEdge=[];this.minorTicks={};this.plotLinesAndBands=[];this.alternateBands={};this.len=0;this.minRange=this.userMinRange=d.minRange||d.maxZoom;this.range=d.range;this.offset=d.offset||0;this.stacks={};this.oldStacks={};this.min=this.max=null;this.crosshair=
l(d.crosshair,na(a.options.tooltip.crosshairs)[c?0:1],!1);var f,d=this.options.events;-1===qb(this,a.axes)&&(c&&!this.isColorAxis?a.axes.splice(a.xAxis.length,0,this):a.axes.push(this),a[this.coll].push(this));this.series=this.series||[];a.inverted&&c&&this.reversed===v&&(this.reversed=!0);this.removePlotLine=this.removePlotBand=this.removePlotBandOrLine;for(f in d)L(this,f,d[f]);this.isLog&&(this.val2lin=Ha,this.lin2val=aa)},setOptions:function(a){this.options=D(this.defaultOptions,this.isXAxis?
{}:this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],D(I[this.coll],a))},defaultLabelFormatter:function(){var a=this.axis,b=this.value,c=a.categories,d=this.dateTimeLabelFormat,e=I.lang.numericSymbols,f=e&&e.length,g,h=a.options.labels.format,a=a.isLog?b:a.tickInterval;if(h)g=ua(h,this);else if(c)g=b;else if(d)g=va(d,b);else if(f&&1E3<=a)for(;f--&&g===v;)c=Math.pow(1E3,f+1),a>=c&&null!==e[f]&&(g=
ba(b/c,-1)+e[f]);g===v&&(g=1E4<=W(b)?ba(b,0):ba(b,-1,v,""));return g},getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();s(a.series,function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries){var d;d=c.options.threshold;var e;a.hasVisibleSeries=!0;a.isLog&&0>=d&&(d=null);a.isXAxis?(d=c.xData,d.length&&(a.dataMin=T(l(a.dataMin,d[0]),wa(d)),a.dataMax=u(l(a.dataMax,d[0]),pa(d)))):(c.getExtremes(),
e=c.dataMax,c=c.dataMin,t(c)&&t(e)&&(a.dataMin=T(l(a.dataMin,c),c),a.dataMax=u(l(a.dataMax,e),e)),t(d)&&(a.dataMin>=d?(a.dataMin=d,a.ignoreMinPadding=!0):a.dataMax<d&&(a.dataMax=d,a.ignoreMaxPadding=!0)))}})},translate:function(a,b,c,d,e,f){var g=1,h=0,k=d?this.oldTransA:this.transA;d=d?this.oldMin:this.min;var m=this.minPixelPadding;e=(this.options.ordinal||this.isLog&&e)&&this.lin2val;k||(k=this.transA);c&&(g*=-1,h=this.len);this.reversed&&(g*=-1,h-=g*(this.sector||this.len));b?(a=a*g+h-m,a=a/k+
d,e&&(a=this.lin2val(a))):(e&&(a=this.val2lin(a)),"between"===f&&(f=.5),a=g*(a-d)*k+h+g*m+($(f)?k*f*this.pointRange:0));return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,d,e){var f=this.chart,g=this.left,h=this.top,k,m,q=c&&f.oldChartHeight||f.chartHeight,p=c&&f.oldChartWidth||f.chartWidth,r;k=this.transB;e=l(e,this.translate(a,null,null,
c));a=c=z(e+k);k=m=z(q-e-k);if(isNaN(e))r=!0;else if(this.horiz){if(k=h,m=q-this.bottom,a<g||a>g+this.width)r=!0}else if(a=g,c=p-this.right,k<h||k>h+this.height)r=!0;return r&&!d?null:f.renderer.crispLine(["M",a,k,"L",c,m],b||1)},getLinearTickPositions:function(a,b,c){var d,e=X(Q(b/a)*a),f=X(ja(c/a)*a),g=[];if(b===c&&$(b))return[b];for(b=e;b<=f;){g.push(b);b=X(b+a);if(b===d)break;d=b}return g},getMinorTickPositions:function(){var a=this.options,b=this.tickPositions,c=this.minorTickInterval,d=[],e;
if(this.isLog)for(e=b.length,a=1;a<e;a++)d=d.concat(this.getLogTickPositions(c,b[a-1],b[a],!0));else if(this.isDatetimeAxis&&"auto"===a.minorTickInterval)d=d.concat(this.getTimeTicks(this.normalizeTimeTickInterval(c),this.min,this.max,a.startOfWeek)),d[0]<this.min&&d.shift();else for(b=this.min+(b[0]-this.min)%c;b<=this.max;b+=c)d.push(b);return d},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,d,e=this.dataMax-this.dataMin>=this.minRange,f,g,h,k,m;this.isXAxis&&this.minRange===
v&&!this.isLog&&(t(a.min)||t(a.max)?this.minRange=null:(s(this.series,function(a){k=a.xData;for(g=m=a.xIncrement?1:k.length-1;0<g;g--)if(h=k[g]-k[g-1],f===v||h<f)f=h}),this.minRange=T(5*f,this.dataMax-this.dataMin)));if(c-b<this.minRange){var q=this.minRange;d=(q-c+b)/2;d=[b-d,l(a.min,b-d)];e&&(d[2]=this.dataMin);b=pa(d);c=[b+q,l(a.max,b+q)];e&&(c[2]=this.dataMax);c=wa(c);c-b<q&&(d[0]=c-q,d[1]=l(a.min,c-q),b=pa(d))}this.min=b;this.max=c},setAxisTranslation:function(a){var b=this,c=b.max-b.min,d=b.axisPointRange||
0,e,f=0,g=0,h=b.linkedParent,k=!!b.categories,m=b.transA;if(b.isXAxis||k||d)h?(f=h.minPointOffset,g=h.pointRangePadding):s(b.series,function(a){var h=k?1:b.isXAxis?a.pointRange:b.axisPointRange||0,m=a.options.pointPlacement,n=a.closestPointRange;h>c&&(h=0);d=u(d,h);f=u(f,ea(m)?0:h/2);g=u(g,"on"===m?0:h);!a.noSharedTooltip&&t(n)&&(e=t(e)?T(e,n):n)}),h=b.ordinalSlope&&e?b.ordinalSlope/e:1,b.minPointOffset=f*=h,b.pointRangePadding=g*=h,b.pointRange=T(d,c),b.closestPointRange=e;a&&(b.oldTransA=m);b.translationSlope=
b.transA=m=b.len/(c+g||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=m*f},setTickPositions:function(a){var b=this,c=b.chart,d=b.options,e=d.startOnTick,f=d.endOnTick,g=b.isLog,h=b.isDatetimeAxis,k=b.isXAxis,m=b.isLinked,q=b.options.tickPositioner,p=d.maxPadding,r=d.minPadding,n=d.tickInterval,F=d.minTickInterval,x=d.tickPixelInterval,E,v=b.categories;m?(b.linkedParent=c[b.coll][d.linkedTo],c=b.linkedParent.getExtremes(),b.min=l(c.min,c.dataMin),b.max=l(c.max,c.dataMax),d.type!==b.linkedParent.options.type&&
N(11,1)):(b.min=l(b.userMin,d.min,b.dataMin),b.max=l(b.userMax,d.max,b.dataMax));g&&(!a&&0>=T(b.min,l(b.dataMin,b.min))&&N(10,1),b.min=X(Ha(b.min)),b.max=X(Ha(b.max)));b.range&&t(b.max)&&(b.userMin=b.min=u(b.min,b.max-b.range),b.userMax=b.max,b.range=null);b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(v||b.axisPointRange||b.usePercentage||m)&&t(b.min)&&t(b.max)&&(c=b.max-b.min)&&(t(d.min)||t(b.userMin)||!r||!(0>b.dataMin)&&b.ignoreMinPadding||(b.min-=c*r),t(d.max)||t(b.userMax)||!p||
!(0<b.dataMax)&&b.ignoreMaxPadding||(b.max+=c*p));$(d.floor)&&(b.min=u(b.min,d.floor));$(d.ceiling)&&(b.max=T(b.max,d.ceiling));b.min===b.max||void 0===b.min||void 0===b.max?b.tickInterval=1:m&&!n&&x===b.linkedParent.options.tickPixelInterval?b.tickInterval=b.linkedParent.tickInterval:(b.tickInterval=l(n,v?1:(b.max-b.min)*x/u(b.len,x)),!t(n)&&b.len<x&&!this.isRadial&&!this.isLog&&!v&&e&&f&&(E=!0,b.tickInterval/=4));k&&!a&&s(b.series,function(a){a.processData(b.min!==b.oldMin||b.max!==b.oldMax)});
b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=b.postProcessTickInterval(b.tickInterval));b.pointRange&&(b.tickInterval=u(b.pointRange,b.tickInterval));!n&&b.tickInterval<F&&(b.tickInterval=F);h||g||n||(b.tickInterval=lb(b.tickInterval,null,J.pow(10,Q(J.log(b.tickInterval)/J.LN10)),l(d.allowDecimals,!(1<b.tickInterval&&5>b.tickInterval&&1E3<b.max&&9999>b.max))));b.minorTickInterval="auto"===d.minorTickInterval&&b.tickInterval?
b.tickInterval/5:d.minorTickInterval;b.tickPositions=a=d.tickPositions?[].concat(d.tickPositions):q&&q.apply(b,[b.min,b.max]);a||(!b.ordinalPositions&&(b.max-b.min)/b.tickInterval>u(2*b.len,200)&&N(19,!0),a=h?b.getTimeTicks(b.normalizeTimeTickInterval(b.tickInterval,d.units),b.min,b.max,d.startOfWeek,b.ordinalPositions,b.closestPointRange,!0):g?b.getLogTickPositions(b.tickInterval,b.min,b.max):b.getLinearTickPositions(b.tickInterval,b.min,b.max),E&&a.splice(1,a.length-2),b.tickPositions=a);m||(d=
a[0],g=a[a.length-1],h=b.minPointOffset||0,e?b.min=d:b.min-h>d&&a.shift(),f?b.max=g:b.max+h<g&&a.pop(),0===a.length&&t(d)&&a.push((g+d)/2),1===a.length&&(e=1E13<W(b.max)?1:.001,b.min-=e,b.max+=e))},setMaxTicks:function(){var a=this.chart,b=a.maxTicks||{},c=this.tickPositions,d=this._maxTicksKey=[this.coll,this.pos,this.len].join("-");!this.isLinked&&!this.isDatetimeAxis&&c&&c.length>(b[d]||0)&&!1!==this.options.alignTicks&&(b[d]=c.length);a.maxTicks=b},adjustTickAmount:function(){var a=this._maxTicksKey,
b=this.tickPositions,c=this.chart.maxTicks;if(c&&c[a]&&!this.isDatetimeAxis&&!this.categories&&!this.isLinked&&!1!==this.options.alignTicks&&this.min!==v){var d=this.tickAmount,e=b.length;this.tickAmount=a=c[a];if(e<a){for(;b.length<a;)b.push(X(b[b.length-1]+this.tickInterval));this.transA*=(e-1)/(a-1);this.max=b[b.length-1]}t(d)&&a!==d&&(this.isDirty=!0)}},setScale:function(){var a=this.stacks,b,c,d,e;this.oldMin=this.min;this.oldMax=this.max;this.oldAxisLength=this.len;this.setAxisSize();e=this.len!==
this.oldAxisLength;s(this.series,function(a){if(a.isDirtyData||a.isDirty||a.xAxis.isDirty)d=!0});if(e||d||this.isLinked||this.forceRedraw||this.userMin!==this.oldUserMin||this.userMax!==this.oldUserMax){if(!this.isXAxis)for(b in a)for(c in a[b])a[b][c].total=null,a[b][c].cum=0;this.forceRedraw=!1;this.getSeriesExtremes();this.setTickPositions();this.oldUserMin=this.userMin;this.oldUserMax=this.userMax;this.isDirty||(this.isDirty=e||this.min!==this.oldMin||this.max!==this.oldMax)}else if(!this.isXAxis)for(b in this.oldStacks&&
(a=this.stacks=this.oldStacks),a)for(c in a[b])a[b][c].cum=a[b][c].total;this.setMaxTicks()},setExtremes:function(a,b,c,d,e){var f=this,g=f.chart;c=l(c,!0);e=y(e,{min:a,max:b});M(f,"setExtremes",e,function(){f.userMin=a;f.userMax=b;f.eventArgs=e;f.isDirtyExtremes=!0;c&&g.redraw(d)})},zoom:function(a,b){var c=this.dataMin,d=this.dataMax,e=this.options;this.allowZoomOutside||(t(c)&&a<=T(c,l(e.min,c))&&(a=v),t(d)&&b>=u(d,l(e.max,d))&&(b=v));this.displayBtn=a!==v||b!==v;this.setExtremes(a,b,!1,v,{trigger:"zoom"});
return!0},setAxisSize:function(){var a=this.chart,b=this.options,c=b.offsetLeft||0,d=this.horiz,e=l(b.width,a.plotWidth-c+(b.offsetRight||0)),f=l(b.height,a.plotHeight),g=l(b.top,a.plotTop),b=l(b.left,a.plotLeft+c),c=/%$/;c.test(f)&&(f=parseInt(f,10)/100*a.plotHeight);c.test(g)&&(g=parseInt(g,10)/100*a.plotHeight+a.plotTop);this.left=b;this.top=g;this.width=e;this.height=f;this.bottom=a.chartHeight-f-g;this.right=a.chartWidth-e-b;this.len=u(d?e:f,0);this.pos=d?b:g},getExtremes:function(){var a=this.isLog;
return{min:a?X(aa(this.min)):this.min,max:a?X(aa(this.max)):this.max,dataMin:this.dataMin,dataMax:this.dataMax,userMin:this.userMin,userMax:this.userMax}},getThreshold:function(a){var b=this.isLog,c=b?aa(this.min):this.min,b=b?aa(this.max):this.max;c>a||null===a?a=c:b<a&&(a=b);return this.translate(a,0,1,0,1)},autoLabelAlign:function(a){a=(l(a,0)-90*this.side+720)%360;return 15<a&&165>a?"right":195<a&&345>a?"left":"center"},getOffset:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.tickPositions,
f=a.ticks,g=a.horiz,h=a.side,k=b.inverted?[1,0,3,2][h]:h,m,q,p=0,r,n=0,F=d.title,x=d.labels,E=0,z=b.axisOffset,b=b.clipOffset,G=[-1,1,1,-1][h],w,y=1,B=l(x.maxStaggerLines,5),A,C,D,H,da;a.hasData=m=a.hasVisibleSeries||t(a.min)&&t(a.max)&&!!e;a.showAxis=q=m||l(d.showEmpty,!0);a.staggerLines=a.horiz&&x.staggerLines;a.axisGroup||(a.gridGroup=c.g("grid").attr({zIndex:d.gridZIndex||1}).add(),a.axisGroup=c.g("axis").attr({zIndex:d.zIndex||2}).add(),a.labelGroup=c.g("axis-labels").attr({zIndex:x.zIndex||
7}).addClass("highcharts-"+a.coll.toLowerCase()+"-labels").add());if(m||a.isLinked){a.labelAlign=l(x.align||a.autoLabelAlign(x.rotation));s(e,function(b){f[b]?f[b].addLabel():f[b]=new ia(a,b)});if(a.horiz&&!a.staggerLines&&B&&!x.rotation){for(m=a.reversed?[].concat(e).reverse():e;y<B;){A=[];C=!1;for(w=0;w<m.length;w++)D=m[w],H=(H=f[D].label&&f[D].label.getBBox())?H.width:0,da=w%y,H&&(D=a.translate(D),A[da]!==v&&D<A[da]&&(C=!0),A[da]=D+H);if(C)y++;else break}1<y&&(a.staggerLines=y)}s(e,function(b){if(0===
h||2===h||{1:"left",3:"right"}[h]===a.labelAlign)E=u(f[b].getLabelSize(),E)});a.staggerLines&&(E*=a.staggerLines,a.labelOffset=E)}else for(w in f)f[w].destroy(),delete f[w];F&&F.text&&!1!==F.enabled&&(a.axisTitle||(a.axisTitle=c.text(F.text,0,0,F.useHTML).attr({zIndex:7,rotation:F.rotation||0,align:F.textAlign||{low:"left",middle:"center",high:"right"}[F.align]}).addClass("highcharts-"+this.coll.toLowerCase()+"-title").css(F.style).add(a.axisGroup),a.axisTitle.isNew=!0),q&&(p=a.axisTitle.getBBox()[g?
"height":"width"],r=F.offset,n=t(r)?0:l(F.margin,g?5:10)),a.axisTitle[q?"show":"hide"]());a.offset=G*l(d.offset,z[h]);c=2===h?a.tickBaseline:0;g=E+n+(E&&G*(g?l(x.y,a.tickBaseline+8):x.x)-c);a.axisTitleMargin=l(r,g);z[h]=u(z[h],a.axisTitleMargin+p+G*a.offset,g);b[k]=u(b[k],2*Q(d.lineWidth/2))},getLinePath:function(a){var b=this.chart,c=this.opposite,d=this.offset,e=this.horiz,f=this.left+(c?this.width:0)+d,d=b.chartHeight-this.bottom-(c?this.height:0)+d;c&&(a*=-1);return b.renderer.crispLine(["M",
e?this.left:f,e?d:this.top,"L",e?b.chartWidth-this.right:f,e?d:b.chartHeight-this.bottom],a)},getTitlePosition:function(){var a=this.horiz,b=this.left,c=this.top,d=this.len,e=this.options.title,f=a?b:c,g=this.opposite,h=this.offset,k=B(e.style.fontSize||12),d={low:f+(a?0:d),middle:f+d/2,high:f+(a?d:0)}[e.align],b=(a?c+this.height:b)+(a?1:-1)*(g?-1:1)*this.axisTitleMargin+(2===this.side?k:0);return{x:a?d:b+(g?this.width:0)+h+(e.x||0),y:a?b-(g?this.height:0)+h:d+(e.y||0)}},render:function(){var a=this,
b=a.horiz,c=a.reversed,d=a.chart,e=d.renderer,f=a.options,g=a.isLog,h=a.isLinked,k=a.tickPositions,m,q=a.axisTitle,p=a.ticks,r=a.minorTicks,n=a.alternateBands,l=f.stackLabels,x=f.alternateGridColor,u=a.tickmarkOffset,w=f.lineWidth,G=d.hasRendered&&t(a.oldMin)&&!isNaN(a.oldMin),y=a.hasData,z=a.showAxis,A,B=f.labels.overflow,C=a.justifyLabels=b&&!1!==B,D;a.labelEdge.length=0;a.justifyToPlot="justify"===B;s([p,r,n],function(a){for(var b in a)a[b].isActive=!1});if(y||h)a.minorTickInterval&&!a.categories&&
s(a.getMinorTickPositions(),function(b){r[b]||(r[b]=new ia(a,b,"minor"));G&&r[b].isNew&&r[b].render(null,!0);r[b].render(null,!1,1)}),k.length&&(m=k.slice(),(b&&c||!b&&!c)&&m.reverse(),C&&(m=m.slice(1).concat([m[0]])),s(m,function(b,c){C&&(c=c===m.length-1?0:c+1);if(!h||b>=a.min&&b<=a.max)p[b]||(p[b]=new ia(a,b)),G&&p[b].isNew&&p[b].render(c,!0,.1),p[b].render(c)}),u&&0===a.min&&(p[-1]||(p[-1]=new ia(a,-1,null,!0)),p[-1].render(-1))),x&&s(k,function(b,c){0===c%2&&b<a.max&&(n[b]||(n[b]=new V.PlotLineOrBand(a)),
A=b+u,D=k[c+1]!==v?k[c+1]+u:a.max,n[b].options={from:g?aa(A):A,to:g?aa(D):D,color:x},n[b].render(),n[b].isActive=!0)}),a._addedPlotLB||(s((f.plotLines||[]).concat(f.plotBands||[]),function(b){a.addPlotBandOrLine(b)}),a._addedPlotLB=!0);s([p,r,n],function(a){var b,c,e=[],f=R?R.duration||500:0,g=function(){for(c=e.length;c--;)a[e[c]]&&!a[e[c]].isActive&&(a[e[c]].destroy(),delete a[e[c]])};for(b in a)a[b].isActive||(a[b].render(b,!1,0),a[b].isActive=!1,e.push(b));a!==n&&d.hasRendered&&f?f&&setTimeout(g,
f):g()});w&&(b=a.getLinePath(w),a.axisLine?a.axisLine.animate({d:b}):a.axisLine=e.path(b).attr({stroke:f.lineColor,"stroke-width":w,zIndex:7}).add(a.axisGroup),a.axisLine[z?"show":"hide"]());q&&z&&(q[q.isNew?"attr":"animate"](a.getTitlePosition()),q.isNew=!1);l&&l.enabled&&a.renderStackTotals();a.isDirty=!1},redraw:function(){this.render();s(this.plotLinesAndBands,function(a){a.render()});s(this.series,function(a){a.isDirty=!0})},destroy:function(a){var b=this,c=b.stacks,d,e=b.plotLinesAndBands;a||
S(b);for(d in c)xa(c[d]),c[d]=null;s([b.ticks,b.minorTicks,b.alternateBands],function(a){xa(a)});for(a=e.length;a--;)e[a].destroy();s("stackTotalGroup axisLine axisTitle axisGroup cross gridGroup labelGroup".split(" "),function(a){b[a]&&(b[a]=b[a].destroy())});this.cross&&this.cross.destroy()},drawCrosshair:function(a,b){if(this.crosshair)if(!1===(t(b)||!l(this.crosshair.snap,!0)))this.hideCrosshair();else{var c,d=this.crosshair,e=d.animation;l(d.snap,!0)?t(b)&&(c=this.chart.inverted!=this.horiz?
b.plotX:this.len-b.plotY):c=this.horiz?a.chartX-this.pos:this.len-a.chartY+this.pos;c=this.isRadial?this.getPlotLinePath(this.isXAxis?b.x:l(b.stackY,b.y)):this.getPlotLinePath(null,null,null,null,c);if(null===c)this.hideCrosshair();else if(this.cross)this.cross.attr({visibility:"visible"})[e?"animate":"attr"]({d:c},e);else e={"stroke-width":d.width||1,stroke:d.color||"#C0C0C0",zIndex:d.zIndex||2},d.dashStyle&&(e.dashstyle=d.dashStyle),this.cross=this.chart.renderer.path(c).attr(e).add()}},hideCrosshair:function(){this.cross&&
this.cross.hide()}};y(Aa.prototype,void 0);var Ra=V.Legend=function(a,b){this.init(a,b)};Ra.prototype={init:function(a,b){var c=this,d=b.itemStyle,e=l(b.padding,8),f=b.itemMarginTop||0;this.options=b;b.enabled&&(c.itemStyle=d,c.itemHiddenStyle=D(d,b.itemHiddenStyle),c.itemMarginTop=f,c.padding=e,c.initialItemX=e,c.initialItemY=e-5,c.maxItemWidth=0,c.chart=a,c.itemHeight=0,c.lastLineHeight=0,c.symbolWidth=l(b.symbolWidth,16),c.pages=[],c.render(),L(c.chart,"endResize",function(){c.positionCheckboxes()}))},
colorizeItem:function(a,b){var c=this.options,d=a.legendItem,e=a.legendLine,f=a.legendSymbol,g=this.itemHiddenStyle.color,c=b?c.itemStyle.color:g,h=b?a.legendColor||a.color||"#CCC":g,g=a.options&&a.options.marker,k={fill:h},m;d&&d.css({fill:c,color:c});e&&e.attr({stroke:h});if(f){if(g&&f.isMarker)for(m in k.stroke=h,g=a.convertAttribs(g),g)d=g[m],d!==v&&(k[m]=d);f.attr(k)}},positionItem:function(a){var b=this.options,c=b.symbolPadding,b=!b.rtl,d=a._legendItemPos,e=d[0],d=d[1],f=a.checkbox;a.legendGroup&&
a.legendGroup.translate(b?e:this.legendWidth-e-2*c-4,d);f&&(f.x=e,f.y=d)},destroyItem:function(a){var b=a.checkbox;s(["legendItem","legendLine","legendSymbol","legendGroup"],function(b){a[b]&&(a[b]=a[b].destroy())});b&&ya(a.checkbox)},destroy:function(){var a=this.group,b=this.box;b&&(this.box=b.destroy());a&&(this.group=a.destroy())},positionCheckboxes:function(a){var b=this.group.alignAttr,c,d=this.clipHeight||this.legendHeight;b&&(c=b.translateY,s(this.allItems,function(e){var f=e.checkbox,g;f&&
(g=c+f.y+(a||0)+3,O(f,{left:b.translateX+e.checkboxOffset+f.x-20+"px",top:g+"px",display:g>c-6&&g<c+d-6?"":"none"}))}))},renderTitle:function(){var a=this.padding,b=this.options.title,c=0;b.text&&(this.title||(this.title=this.chart.renderer.label(b.text,a-3,a-4,null,null,null,null,null,"legend-title").attr({zIndex:1}).css(b.style).add(this.group)),a=this.title.getBBox(),c=a.height,this.offsetWidth=a.width,this.contentGroup.attr({translateY:c}));this.titleHeight=c},renderItem:function(a){var b=this.chart,
c=b.renderer,d=this.options,e="horizontal"===d.layout,f=this.symbolWidth,g=d.symbolPadding,h=this.itemStyle,k=this.itemHiddenStyle,m=this.padding,q=e?l(d.itemDistance,20):0,p=!d.rtl,r=d.width,n=d.itemMarginBottom||0,s=this.itemMarginTop,x=this.initialItemX,t=a.legendItem,v=a.series&&a.series.drawLegendSymbol?a.series:a,w=v.options,w=this.createCheckboxForItem&&w&&w.showCheckbox,y=d.useHTML;t||(a.legendGroup=c.g("legend-item").attr({zIndex:1}).add(this.scrollGroup),a.legendItem=t=c.text(d.labelFormat?
ua(d.labelFormat,a):d.labelFormatter.call(a),p?f+g:-g,this.baseline||0,y).css(D(a.visible?h:k)).attr({align:p?"left":"right",zIndex:2}).add(a.legendGroup),this.baseline||(this.baseline=c.fontMetrics(h.fontSize,t).f+3+s,t.attr("y",this.baseline)),v.drawLegendSymbol(this,a),this.setItemEvents&&this.setItemEvents(a,t,y,h,k),this.colorizeItem(a,a.visible),w&&this.createCheckboxForItem(a));c=t.getBBox();f=a.checkboxOffset=d.itemWidth||a.legendItemWidth||f+g+c.width+q+(w?20:0);this.itemHeight=g=z(a.legendItemHeight||
c.height);e&&this.itemX-x+f>(r||b.chartWidth-2*m-x-d.x)&&(this.itemX=x,this.itemY+=s+this.lastLineHeight+n,this.lastLineHeight=0);this.maxItemWidth=u(this.maxItemWidth,f);this.lastItemY=s+this.itemY+n;this.lastLineHeight=u(g,this.lastLineHeight);a._legendItemPos=[this.itemX,this.itemY];e?this.itemX+=f:(this.itemY+=s+g+n,this.lastLineHeight=g);this.offsetWidth=r||u((e?this.itemX-x-q:f)+m,this.offsetWidth)},getAllItems:function(){var a=[];s(this.chart.series,function(b){var c=b.options;l(c.showInLegend,
t(c.linkedTo)?!1:v,!0)&&(a=a.concat(b.legendItems||("point"===c.legendType?b.data:b)))});return a},render:function(){var a=this,b=a.chart,c=b.renderer,d=a.group,e,f,g,h,k=a.box,m=a.options,q=a.padding,p=m.borderWidth,l=m.backgroundColor;a.itemX=a.initialItemX;a.itemY=a.initialItemY;a.offsetWidth=0;a.lastItemY=0;d||(a.group=d=c.g("legend").attr({zIndex:7}).add(),a.contentGroup=c.g().attr({zIndex:1}).add(d),a.scrollGroup=c.g().add(a.contentGroup));a.renderTitle();e=a.getAllItems();Ja(e,function(a,b){return(a.options&&
a.options.legendIndex||0)-(b.options&&b.options.legendIndex||0)});m.reversed&&e.reverse();a.allItems=e;a.display=f=!!e.length;s(e,function(b){a.renderItem(b)});g=m.width||a.offsetWidth;h=a.lastItemY+a.lastLineHeight+a.titleHeight;h=a.handleOverflow(h);if(p||l)g+=q,h+=q,k?0<g&&0<h&&(k[k.isNew?"attr":"animate"](k.crisp({width:g,height:h})),k.isNew=!1):(a.box=k=c.rect(0,0,g,h,m.borderRadius,p||0).attr({stroke:m.borderColor,"stroke-width":p||0,fill:l||"none"}).add(d).shadow(m.shadow),k.isNew=!0),k[f?
"show":"hide"]();a.legendWidth=g;a.legendHeight=h;s(e,function(b){a.positionItem(b)});f&&d.align(y({width:g,height:h},m),!0,"spacingBox");b.isResizing||this.positionCheckboxes()},handleOverflow:function(a){var b=this,c=this.chart,d=c.renderer,e=this.options,f=e.y,f=c.spacingBox.height+("top"===e.verticalAlign?-f:f)-this.padding,g=e.maxHeight,h,k=this.clipRect,m=e.navigation,q=l(m.animation,!0),p=m.arrowSize||12,r=this.nav,n=this.pages,t,x=this.allItems;"horizontal"===e.layout&&(f/=2);g&&(f=T(f,g));
n.length=0;a>f&&!e.useHTML?(this.clipHeight=h=u(f-20-this.titleHeight-this.padding,0),this.currentPage=l(this.currentPage,1),this.fullHeight=a,s(x,function(a,b){var c=a._legendItemPos[1],d=z(a.legendItem.getBBox().height),e=n.length;if(!e||c-n[e-1]>h&&(t||c)!==n[e-1])n.push(t||c),e++;b===x.length-1&&c+d-n[e-1]>h&&n.push(c);c!==t&&(t=c)}),k||(k=b.clipRect=d.clipRect(0,this.padding,9999,0),b.contentGroup.clip(k)),k.attr({height:h}),r||(this.nav=r=d.g().attr({zIndex:1}).add(this.group),this.up=d.symbol("triangle",
0,0,p,p).on("click",function(){b.scroll(-1,q)}).add(r),this.pager=d.text("",15,10).css(m.style).add(r),this.down=d.symbol("triangle-down",0,0,p,p).on("click",function(){b.scroll(1,q)}).add(r)),b.scroll(0),a=f):r&&(k.attr({height:c.chartHeight}),r.hide(),this.scrollGroup.attr({translateY:1}),this.clipHeight=0);return a},scroll:function(a,b){var c=this.pages,d=c.length,e=this.currentPage+a,f=this.clipHeight,g=this.options.navigation,h=g.activeColor,g=g.inactiveColor,k=this.pager,m=this.padding;e>d&&
(e=d);0<e&&(b!==v&&(R=l(b,this.chart.animation)),this.nav.attr({translateX:m,translateY:f+this.padding+7+this.titleHeight,visibility:"visible"}),this.up.attr({fill:1===e?g:h}).css({cursor:1===e?"default":"pointer"}),k.attr({text:e+"/"+d}),this.down.attr({x:18+this.pager.getBBox().width,fill:e===d?g:h}).css({cursor:e===d?"default":"pointer"}),c=-c[e-1]+this.initialItemY,this.scrollGroup.animate({translateY:c}),this.currentPage=e,this.positionCheckboxes(c))}};var ub=V.LegendSymbolMixin={drawRectangle:function(a,
b){var c=a.options.symbolHeight||12;b.legendSymbol=this.chart.renderer.rect(0,a.baseline-5-c/2,a.symbolWidth,c,a.options.symbolRadius||0).attr({zIndex:3}).add(b.legendGroup)},drawLineMarker:function(a){var b=this.options,c=b.marker,d;d=a.symbolWidth;var e=this.chart.renderer,f=this.legendGroup;a=a.baseline-z(.3*e.fontMetrics(a.options.itemStyle.fontSize,this.legendItem).b);var g;b.lineWidth&&(g={"stroke-width":b.lineWidth},b.dashStyle&&(g.dashstyle=b.dashStyle),this.legendLine=e.path(["M",0,a,"L",
d,a]).attr(g).add(f));c&&!1!==c.enabled&&(b=c.radius,this.legendSymbol=d=e.symbol(this.symbol,d/2-b,a-b,2*b,2*b).add(f),d.isMarker=!0)}};(/Trident\/7\.0/.test(ha)||Ca)&&Ia(Ra.prototype,"positionItem",function(a,b){var c=this,d=function(){b._legendItemPos&&a.call(c,b)};d();setTimeout(d)});Ka.prototype={init:function(a,b){var c,d=a.series;a.series=null;c=D(I,a);c.series=a.series=d;this.userOptions=a;d=c.chart;this.margin=this.splashArray("margin",d);this.spacing=this.splashArray("spacing",d);var e=
d.events;this.bounds={h:{},v:{}};this.callback=b;this.isResizing=0;this.options=c;this.axes=[];this.series=[];this.hasCartesianSeries=d.showAxes;var f=this,g;f.index=ca.length;ca.push(f);gb++;!1!==d.reflow&&L(f,"load",function(){f.initReflow()});if(e)for(g in e)L(f,g,e[g]);f.xAxis=[];f.yAxis=[];f.animation=Y?!1:l(d.animation,!0);f.pointCount=f.colorCounter=f.symbolCounter=0;f.firstRender()},initSeries:function(a){var b=this.options.chart;(b=ra[a.type||b.type||b.defaultSeriesType])||N(17,!0);b=new b;
b.init(this,a);return b},isInsidePlot:function(a,b,c){var d=c?b:a;a=c?a:b;return 0<=d&&d<=this.plotWidth&&0<=a&&a<=this.plotHeight},adjustTickAmounts:function(){!1!==this.options.chart.alignTicks&&s(this.axes,function(a){a.adjustTickAmount()});this.maxTicks=null},redraw:function(a){var b=this.axes,c=this.series,d=this.pointer,e=this.legend,f=this.isDirtyLegend,g,h,k=this.hasCartesianSeries,m=this.isDirtyBox,q=c.length,p=q,r=this.renderer,n=r.isHidden(),t=[];R=l(a,this.animation);n&&this.cloneRenderTo();
for(this.layOutTitles();p--;)if(a=c[p],a.options.stacking&&(g=!0,a.isDirty)){h=!0;break}if(h)for(p=q;p--;)a=c[p],a.options.stacking&&(a.isDirty=!0);s(c,function(a){a.isDirty&&"point"===a.options.legendType&&(f=!0)});f&&e.options.enabled&&(e.render(),this.isDirtyLegend=!1);g&&this.getStacks();k&&(this.isResizing||(this.maxTicks=null,s(b,function(a){a.setScale()})),this.adjustTickAmounts());this.getMargins();k&&(s(b,function(a){a.isDirty&&(m=!0)}),s(b,function(a){a.isDirtyExtremes&&(a.isDirtyExtremes=
!1,t.push(function(){M(a,"afterSetExtremes",y(a.eventArgs,a.getExtremes()));delete a.eventArgs}));(m||g)&&a.redraw()}));m&&this.drawChartBox();s(c,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});d&&d.reset(!0);r.draw();M(this,"redraw");n&&this.cloneRenderTo(!0);s(t,function(a){a.call()})},get:function(a){var b=this.axes,c=this.series,d,e;for(d=0;d<b.length;d++)if(b[d].options.id===a)return b[d];for(d=0;d<c.length;d++)if(c[d].options.id===a)return c[d];for(d=0;d<c.length;d++)for(e=
c[d].points||[],b=0;b<e.length;b++)if(e[b].id===a)return e[b];return null},getAxes:function(){var a=this,b=this.options,c=b.xAxis=na(b.xAxis||{}),b=b.yAxis=na(b.yAxis||{});s(c,function(a,b){a.index=b;a.isX=!0});s(b,function(a,b){a.index=b});c=c.concat(b);s(c,function(b){new Aa(a,b)});a.adjustTickAmounts()},getSelectedPoints:function(){var a=[];s(this.series,function(b){a=a.concat(hb(b.points||[],function(a){return a.selected}))});return a},getSelectedSeries:function(){return hb(this.series,function(a){return a.selected})},
getStacks:function(){var a=this;s(a.yAxis,function(a){a.stacks&&a.hasVisibleSeries&&(a.oldStacks=a.stacks)});s(a.series,function(b){!b.options.stacking||!0!==b.visible&&!1!==a.options.chart.ignoreHiddenSeries||(b.stackKey=b.type+l(b.options.stack,""))})},setTitle:function(a,b,c){var d=this,e=d.options,f;f=e.title=D(e.title,a);e=e.subtitle=D(e.subtitle,b);s([["title",a,f],["subtitle",b,e]],function(a){var b=a[0],c=d[b],e=a[1];a=a[2];c&&e&&(d[b]=c=c.destroy());a&&a.text&&!c&&(d[b]=d.renderer.text(a.text,
0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:a.zIndex||4}).css(a.style).add())});d.layOutTitles(c)},layOutTitles:function(a){var b=0,c=this.title,d=this.subtitle,e=this.options,f=e.title,e=e.subtitle,g=this.renderer,h=this.spacingBox.width-44;c&&(c.css({width:(f.width||h)+"px"}).align(y({y:g.fontMetrics(f.style.fontSize,c).b-3},f),!1,"spacingBox"),f.floating||f.verticalAlign||(b=c.getBBox().height));d&&(d.css({width:(e.width||h)+"px"}).align(y({y:b+(f.margin-13)+g.fontMetrics(f.style.fontSize,
d).b},e),!1,"spacingBox"),e.floating||e.verticalAlign||(b=ja(b+d.getBBox().height)));c=this.titleOffset!==b;this.titleOffset=b;!this.isDirtyBox&&c&&(this.isDirtyBox=c,this.hasRendered&&l(a,!0)&&this.isDirtyBox&&this.redraw())},getChartSize:function(){var a=this.options.chart,b=a.width,a=a.height,c=this.renderToClone||this.renderTo;t(b)||(this.containerWidth=Ea(c,"width"));t(a)||(this.containerHeight=Ea(c,"height"));this.chartWidth=u(0,b||this.containerWidth||600);this.chartHeight=u(0,l(a,19<this.containerHeight?
this.containerHeight:400))},cloneRenderTo:function(a){var b=this.renderToClone,c=this.container;a?b&&(this.renderTo.appendChild(c),ya(b),delete this.renderToClone):(c&&c.parentNode===this.renderTo&&this.renderTo.removeChild(c),this.renderToClone=b=this.renderTo.cloneNode(0),O(b,{position:"absolute",top:"-9999px",display:"block"}),b.style.setProperty&&b.style.setProperty("display","block","important"),A.body.appendChild(b),c&&b.appendChild(c))},getContainer:function(){var a,b=this.options.chart,c,
d,e;this.renderTo=a=b.renderTo;e="highcharts-"+La++;ea(a)&&(this.renderTo=a=A.getElementById(a));a||N(13,!0);c=B(C(a,"data-highcharts-chart"));!isNaN(c)&&ca[c]&&ca[c].hasRendered&&ca[c].destroy();C(a,"data-highcharts-chart",this.index);a.innerHTML="";b.skipClone||a.offsetWidth||this.cloneRenderTo();this.getChartSize();c=this.chartWidth;d=this.chartHeight;this.container=a=oa("div",{className:"highcharts-container"+(b.className?" "+b.className:""),id:e},y({position:"relative",overflow:"hidden",width:c+
"px",height:d+"px",textAlign:"left",lineHeight:"normal",zIndex:0,"-webkit-tap-highlight-color":"rgba(0,0,0,0)"},b.style),this.renderToClone||a);this._cursor=a.style.cursor;this.renderer=b.forExport?new ta(a,c,d,b.style,!0):new ta(a,c,d,b.style);Y&&this.renderer.create(this,a,c,d)},getMargins:function(){var a=this.spacing,b,c=this.legend,d=this.margin,e=this.options.legend,f=l(e.margin,20),g=e.x,h=e.y,k=e.align,m=e.verticalAlign,q=this.titleOffset;this.resetMargins();b=this.axisOffset;q&&!t(d[0])&&
(this.plotTop=u(this.plotTop,q+this.options.title.margin+a[0]));c.display&&!e.floating&&("right"===k?t(d[1])||(this.marginRight=u(this.marginRight,c.legendWidth-g+f+a[1])):"left"===k?t(d[3])||(this.plotLeft=u(this.plotLeft,c.legendWidth+g+f+a[3])):"top"===m?t(d[0])||(this.plotTop=u(this.plotTop,c.legendHeight+h+f+a[0])):"bottom"!==m||t(d[2])||(this.marginBottom=u(this.marginBottom,c.legendHeight-h+f+a[2])));this.extraBottomMargin&&(this.marginBottom+=this.extraBottomMargin);this.extraTopMargin&&(this.plotTop+=
this.extraTopMargin);this.hasCartesianSeries&&s(this.axes,function(a){a.getOffset()});t(d[3])||(this.plotLeft+=b[3]);t(d[0])||(this.plotTop+=b[0]);t(d[2])||(this.marginBottom+=b[2]);t(d[1])||(this.marginRight+=b[1]);this.setChartSize()},reflow:function(a){var b=this,c=b.options.chart,d=b.renderTo,e=c.width||Ea(d,"width"),f=c.height||Ea(d,"height"),c=a?a.target:w,d=function(){b.container&&(b.setSize(e,f,!1),b.hasUserSize=null)};if(!b.hasUserSize&&e&&f&&(c===w||c===A)){if(e!==b.containerWidth||f!==
b.containerHeight)clearTimeout(b.reflowTimeout),a?b.reflowTimeout=setTimeout(d,100):d();b.containerWidth=e;b.containerHeight=f}},initReflow:function(){var a=this,b=function(b){a.reflow(b)};L(w,"resize",b);L(a,"destroy",function(){S(w,"resize",b)})},setSize:function(a,b,c){var d=this,e,f,g;d.isResizing+=1;g=function(){d&&M(d,"endResize",null,function(){--d.isResizing})};R=l(c,d.animation);d.oldChartHeight=d.chartHeight;d.oldChartWidth=d.chartWidth;t(a)&&(d.chartWidth=e=u(0,z(a)),d.hasUserSize=!!e);
t(b)&&(d.chartHeight=f=u(0,z(b)));(R?jb:O)(d.container,{width:e+"px",height:f+"px"},R);d.setChartSize(!0);d.renderer.setSize(e,f,c);d.maxTicks=null;s(d.axes,function(a){a.isDirty=!0;a.setScale()});s(d.series,function(a){a.isDirty=!0});d.isDirtyLegend=!0;d.isDirtyBox=!0;d.layOutTitles();d.getMargins();d.redraw(c);d.oldChartHeight=null;M(d,"resize");!1===R?g():setTimeout(g,R&&R.duration||500)},setChartSize:function(a){var b=this.inverted,c=this.renderer,d=this.chartWidth,e=this.chartHeight,f=this.options.chart,
g=this.spacing,h=this.clipOffset,k,m,q,p;this.plotLeft=k=z(this.plotLeft);this.plotTop=m=z(this.plotTop);this.plotWidth=q=u(0,z(d-k-this.marginRight));this.plotHeight=p=u(0,z(e-m-this.marginBottom));this.plotSizeX=b?p:q;this.plotSizeY=b?q:p;this.plotBorderWidth=f.plotBorderWidth||0;this.spacingBox=c.spacingBox={x:g[3],y:g[0],width:d-g[3]-g[1],height:e-g[0]-g[2]};this.plotBox=c.plotBox={x:k,y:m,width:q,height:p};d=2*Q(this.plotBorderWidth/2);b=ja(u(d,h[3])/2);c=ja(u(d,h[0])/2);this.clipBox={x:b,y:c,
width:Q(this.plotSizeX-u(d,h[1])/2-b),height:u(0,Q(this.plotSizeY-u(d,h[2])/2-c))};a||s(this.axes,function(a){a.setAxisSize();a.setAxisTranslation()})},resetMargins:function(){var a=this.spacing,b=this.margin;this.plotTop=l(b[0],a[0]);this.marginRight=l(b[1],a[1]);this.marginBottom=l(b[2],a[2]);this.plotLeft=l(b[3],a[3]);this.axisOffset=[0,0,0,0];this.clipOffset=[0,0,0,0]},drawChartBox:function(){var a=this.options.chart,b=this.renderer,c=this.chartWidth,d=this.chartHeight,e=this.chartBackground,
f=this.plotBackground,g=this.plotBorder,h=this.plotBGImage,k=a.borderWidth||0,m=a.backgroundColor,q=a.plotBackgroundColor,p=a.plotBackgroundImage,l=a.plotBorderWidth||0,n,s=this.plotLeft,t=this.plotTop,u=this.plotWidth,v=this.plotHeight,w=this.plotBox,y=this.clipRect,z=this.clipBox;n=k+(a.shadow?8:0);if(k||m)e?e.animate(e.crisp({width:c-n,height:d-n})):(e={fill:m||"none"},k&&(e.stroke=a.borderColor,e["stroke-width"]=k),this.chartBackground=b.rect(n/2,n/2,c-n,d-n,a.borderRadius,k).attr(e).addClass("highcharts-background").add().shadow(a.shadow));
q&&(f?f.animate(w):this.plotBackground=b.rect(s,t,u,v,0).attr({fill:q}).add().shadow(a.plotShadow));p&&(h?h.animate(w):this.plotBGImage=b.image(p,s,t,u,v).add());y?y.animate({width:z.width,height:z.height}):this.clipRect=b.clipRect(z);l&&(g?g.animate(g.crisp({x:s,y:t,width:u,height:v,strokeWidth:-l})):this.plotBorder=b.rect(s,t,u,v,0,-l).attr({stroke:a.plotBorderColor,"stroke-width":l,fill:"none",zIndex:1}).add());this.isDirtyBox=!1},propFromSeries:function(){var a=this,b=a.options.chart,c,d=a.options.series,
e,f;s(["inverted","angular","polar"],function(g){c=ra[b.type||b.defaultSeriesType];f=a[g]||b[g]||c&&c.prototype[g];for(e=d&&d.length;!f&&e--;)(c=ra[d[e].type])&&c.prototype[g]&&(f=!0);a[g]=f})},linkSeries:function(){var a=this,b=a.series;s(b,function(a){a.linkedSeries.length=0});s(b,function(b){var d=b.options.linkedTo;ea(d)&&(d=":previous"===d?a.series[b.index-1]:a.get(d))&&(d.linkedSeries.push(b),b.linkedParent=d)})},renderSeries:function(){s(this.series,function(a){a.translate();a.setTooltipPoints&&
a.setTooltipPoints();a.render()})},renderLabels:function(){var a=this,b=a.options.labels;b.items&&s(b.items,function(c){var d=y(b.style,c.style),e=B(d.left)+a.plotLeft,f=B(d.top)+a.plotTop+12;delete d.left;delete d.top;a.renderer.text(c.html,e,f).attr({zIndex:2}).css(d).add()})},render:function(){var a=this.axes,b=this.renderer,c=this.options;this.setTitle();this.legend=new Ra(this,c.legend);this.getStacks();s(a,function(a){a.setScale()});this.getMargins();this.maxTicks=null;s(a,function(a){a.setTickPositions(!0);
a.setMaxTicks()});this.adjustTickAmounts();this.getMargins();this.drawChartBox();this.hasCartesianSeries&&s(a,function(a){a.render()});this.seriesGroup||(this.seriesGroup=b.g("series-group").attr({zIndex:3}).add());this.renderSeries();this.renderLabels();this.showCredits(c.credits);this.hasRendered=!0},showCredits:function(a){a.enabled&&!this.credits&&(this.credits=this.renderer.text(a.text,0,0).on("click",function(){a.href&&(location.href=a.href)}).attr({align:a.position.align,zIndex:8}).css(a.style).add().align(a.position))},
destroy:function(){var a=this,b=a.axes,c=a.series,d=a.container,e,f=d&&d.parentNode;M(a,"destroy");ca[a.index]=v;gb--;a.renderTo.removeAttribute("data-highcharts-chart");S(a);for(e=b.length;e--;)b[e]=b[e].destroy();for(e=c.length;e--;)c[e]=c[e].destroy();s("title subtitle chartBackground plotBackground plotBGImage plotBorder seriesGroup clipRect credits pointer scroller rangeSelector legend resetZoomButton tooltip renderer".split(" "),function(b){var c=a[b];c&&c.destroy&&(a[b]=c.destroy())});d&&(d.innerHTML=
"",S(d),f&&ya(d));for(e in a)delete a[e]},isReadyToRender:function(){var a=this;return!P&&w==w.top&&"complete"!==A.readyState||Y&&!w.canvg?(Y?CanVGController.push(function(){a.firstRender()},a.options.global.canvasToolsURL):A.attachEvent("onreadystatechange",function(){A.detachEvent("onreadystatechange",a.firstRender);"complete"===A.readyState&&a.firstRender()}),!1):!0},firstRender:function(){var a=this,b=a.options,c=a.callback;a.isReadyToRender()&&(a.getContainer(),M(a,"init"),a.resetMargins(),a.setChartSize(),
a.propFromSeries(),a.getAxes(),s(b.series||[],function(b){a.initSeries(b)}),a.linkSeries(),M(a,"beforeRender"),V.Pointer&&(a.pointer=new Pointer(a,b)),a.render(),a.renderer.draw(),c&&c.apply(a,[a]),s(a.callbacks,function(b){b.apply(a,[a])}),a.cloneRenderTo(!0),M(a,"load"))},splashArray:function(a,b){var c=b[a],c=Z(c)?c:[c,c,c,c];return[l(b[a+"Top"],c[0]),l(b[a+"Right"],c[1]),l(b[a+"Bottom"],c[2]),l(b[a+"Left"],c[3])]}};Ka.prototype.callbacks=[];var Ga=function(){};Ga.prototype={init:function(a,b,
c){this.series=a;this.applyOptions(b,c);this.pointAttr={};a.options.colorByPoint&&(b=a.options.colors||a.chart.options.colors,this.color=this.color||b[a.colorCounter++],a.colorCounter===b.length&&(a.colorCounter=0));a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=c.options.pointValKey||c.pointValKey;a=Ga.prototype.optionsToObject.call(this,a);y(this,a);this.options=this.options?y(this.options,a):a;d&&(this.y=this[d]);this.x===v&&c&&(this.x=b===v?c.autoIncrement():
b);return this},optionsToObject:function(a){var b={},c=this.series,d=c.pointArrayMap||["y"],e=d.length,f=0,g=0;if("number"===typeof a||null===a)b[d[0]]=a;else if(la(a))for(a.length>e&&(c=typeof a[0],"string"===c?b.name=a[0]:"number"===c&&(b.x=a[0]),f++);g<e;)b[d[g++]]=a[f++];else"object"===typeof a&&(b=a,a.dataLabels&&(c._hasPointLabels=!0),a.marker&&(c._hasPointMarkers=!0));return b},destroy:function(){var a=this.series.chart,b=a.hoverPoints,c;a.pointCount--;b&&(this.setState(),ma(b,this),b.length||
(a.hoverPoints=null));if(this===a.hoverPoint)this.onMouseOut();if(this.graphic||this.dataLabel)S(this),this.destroyElements();this.legendItem&&a.legend.destroyItem(this);for(c in this)this[c]=null},destroyElements:function(){for(var a="graphic dataLabel dataLabelUpper group connector shadowGroup".split(" "),b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,y:this.y,key:this.name||this.category,series:this.series,point:this,percentage:this.percentage,
total:this.total||this.stackTotal}},tooltipFormatter:function(a){var b=this.series,c=b.tooltipOptions,d=l(c.valueDecimals,""),e=c.valuePrefix||"",f=c.valueSuffix||"";s(b.pointArrayMap||["y"],function(b){b="{point."+b;if(e||f)a=a.replace(b+"}",e+b+"}"+f);a=a.replace(b+"}",b+":,."+d+"f}")});return ua(a,{point:this,series:this.series})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&this.importEvents();"click"===
a&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});M(this,a,b,c)}};var Sa=function(){};Sa.prototype={isCartesian:!0,type:"line",pointClass:Ga,sorted:!0,requireSorting:!0,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},axisTypes:["xAxis","yAxis"],colorCounter:0,parallelArrays:["x","y"],init:function(a,b){var c=this,d,e,f=a.series,g=function(a,b){return l(a.options.index,a._i)-l(b.options.index,b._i)};c.chart=a;c.options=
b=c.setOptions(b);c.linkedSeries=[];c.bindAxes();y(c,{name:b.name,state:"",pointAttr:{},visible:!1!==b.visible,selected:!0===b.selected});Y&&(b.animation=!1);e=b.events;for(d in e)L(c,d,e[d]);if(e&&e.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;c.getColor();c.getSymbol();s(c.parallelArrays,function(a){c[a+"Data"]=[]});c.setData(b.data,!1);c.isCartesian&&(a.hasCartesianSeries=!0);f.push(c);c._i=f.length-1;Ja(f,g);this.yAxis&&Ja(this.yAxis.series,g);
s(f,function(a,b){a.index=b;a.name=a.name||"Series "+(b+1)})},bindAxes:function(){var a=this,b=a.options,c=a.chart,d;s(a.axisTypes||[],function(e){s(c[e],function(c){d=c.options;if(b[e]===d.index||b[e]!==v&&b[e]===d.id||b[e]===v&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0});a[e]||a.optionalAxis===e||N(18,!0)})},updateParallelArrays:function(a,b){var c=a.series,d=arguments;s(c.parallelArrays,"number"===typeof b?function(d){var f="y"===d&&c.toYData?c.toYData(a):a[d];c[d+"Data"][b]=f}:function(a){Array.prototype[b].apply(c[a+
"Data"],Array.prototype.slice.call(d,2))})},autoIncrement:function(){var a=this.options,b=this.xIncrement,b=l(b,a.pointStart,0);this.pointInterval=l(this.pointInterval,a.pointInterval,1);this.xIncrement=b+this.pointInterval;return b},getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);d.length&&(b=[d])}else s(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=
b},setOptions:function(a){var b=this.chart,c=b.options.plotOptions,b=b.userOptions||{},d=b.plotOptions||{},e=c[this.type];this.userOptions=a;c=D(e,c.series,a);this.tooltipOptions=D(I.tooltip,I.plotOptions[this.type].tooltip,b.tooltip,d.series&&d.series.tooltip,d[this.type]&&d[this.type].tooltip,a.tooltip);null===e.marker&&delete c.marker;return c},getCyclic:function(a,b,c){var d=this.userOptions,e="_"+a+"Index",f=a+"Counter";b||(t(d[e])?b=d[e]:(d[e]=b=this.chart[f]%c.length,this.chart[f]+=1),b=c[b]);
this[a]=b},getColor:function(){this.options.colorByPoint||this.getCyclic("color",this.options.color||Pa[this.type].color,this.chart.options.colors)},getSymbol:function(){var a=this.options.marker;this.getCyclic("symbol",a.symbol,this.chart.options.symbols);/^url/.test(this.symbol)&&(a.radius=0)},drawLegendSymbol:ub.drawLineMarker,setData:function(a,b,c,d){var e=this,f=e.points,g=f&&f.length||0,h,k=e.options,m=e.chart,q=null,p=e.xAxis,r=p&&!!p.categories,n=e.tooltipPoints,t=k.turboThreshold,x=this.xData,
u=this.yData,w=(h=e.pointArrayMap)&&h.length;a=a||[];h=a.length;b=l(b,!0);if(!1===d||!h||g!==h||e.cropped||e.hasGroupedData){e.xIncrement=null;e.pointRange=r?1:k.pointRange;e.colorCounter=0;s(this.parallelArrays,function(a){e[a+"Data"].length=0});if(t&&h>t){for(c=0;null===q&&c<h;)q=a[c],c++;if($(q)){r=l(k.pointStart,0);k=l(k.pointInterval,1);for(c=0;c<h;c++)x[c]=r,u[c]=a[c],r+=k;e.xIncrement=r}else if(la(q))if(w)for(c=0;c<h;c++)k=a[c],x[c]=k[0],u[c]=k.slice(1,w+1);else for(c=0;c<h;c++)k=a[c],x[c]=
k[0],u[c]=k[1];else N(12)}else for(c=0;c<h;c++)a[c]!==v&&(k={series:e},e.pointClass.prototype.applyOptions.apply(k,[a[c]]),e.updateParallelArrays(k,c),r&&k.name&&(p.names[k.x]=k.name));ea(u[0])&&N(14,!0);e.data=[];e.options.data=a;for(c=g;c--;)f[c]&&f[c].destroy&&f[c].destroy();n&&(n.length=0);p&&(p.minRange=p.userMinRange);e.isDirty=e.isDirtyData=m.isDirtyBox=!0;c=!1}else s(a,function(a,b){f[b].update(a,!1,null,!1)});b&&m.redraw(c)},processData:function(a){var b=this.xData,c=this.yData,d=b.length,
e;e=0;var f,g,h=this.xAxis,k,m=this.options;k=m.cropThreshold;var q=0,p=this.isCartesian,l,n;if(p&&!this.isDirty&&!h.isDirty&&!this.yAxis.isDirty&&!a)return!1;h&&(l=h.getExtremes(),n=l.min,l=l.max);if(p&&this.sorted&&(!k||d>k||this.forceCrop))if(b[d-1]<n||b[0]>l)b=[],c=[];else if(b[0]<n||b[d-1]>l)e=this.cropData(this.xData,this.yData,n,l),b=e.xData,c=e.yData,e=e.start,f=!0,q=b.length;for(k=b.length-1;0<=k;k--)d=b[k]-b[k-1],!f&&b[k]>n&&b[k]<l&&q++,0<d&&(g===v||d<g)?g=d:0>d&&this.requireSorting&&N(15);
this.cropped=f;this.cropStart=e;this.processedXData=b;this.processedYData=c;this.activePointCount=q;null===m.pointRange&&(this.pointRange=g||1);this.closestPointRange=g},cropData:function(a,b,c,d){var e=a.length,f=0,g=e,h=l(this.cropShoulder,1),k;for(k=0;k<e;k++)if(a[k]>=c){f=u(0,k-h);break}for(;k<e;k++)if(a[k]>d){g=k+h;break}return{xData:a.slice(f,g),yData:b.slice(f,g),start:f,end:g}},generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,
g=d.length,h=this.cropStart||0,k,m=this.hasGroupedData,q,l=[],r;b||m||(b=[],b.length=a.length,b=this.data=b);for(r=0;r<g;r++)k=h+r,m?l[r]=(new f).init(this,[d[r]].concat(na(e[r]))):(b[k]?q=b[k]:a[k]!==v&&(b[k]=q=(new f).init(this,a[k],d[r])),l[r]=q),l[r].index=k;if(b&&(g!==(c=b.length)||m))for(r=0;r<c;r++)r!==h||m||(r+=g),b[r]&&(b[r].destroyElements(),b[r].plotX=v);this.data=b;this.points=l},getExtremes:function(a){var b=this.yAxis,c=this.processedXData,d,e=[],f=0;d=this.xAxis.getExtremes();var g=
d.min,h=d.max,k,m,q,p;a=a||this.stackedYData||this.processedYData;d=a.length;for(p=0;p<d;p++)if(m=c[p],q=a[p],k=null!==q&&q!==v&&(!b.isLog||q.length||0<q),m=this.getExtremesFromAll||this.cropped||(c[p+1]||m)>=g&&(c[p-1]||m)<=h,k&&m)if(k=q.length)for(;k--;)null!==q[k]&&(e[f++]=q[k]);else e[f++]=q;this.dataMin=l(void 0,wa(e));this.dataMax=l(void 0,pa(e))},translate:function(){this.processedXData||this.processData();this.generatePoints();for(var a=this.options,b=a.stacking,c=this.xAxis,d=c.categories,
e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,k=a.pointPlacement,m="between"===k||$(k),q=a.threshold,a=0;a<g;a++){var p=f[a],r=p.x,n=p.y,s=p.low,u=b&&e.stacks[(this.negStacks&&n<q?"-":"")+this.stackKey];e.isLog&&0>=n&&(p.y=n=null,N(10));p.plotX=c.translate(r,0,0,0,1,k,"flags"===this.type);b&&this.visible&&u&&u[r]&&(u=u[r],n=u.points[this.index+","+a],s=n[0],n=n[1],0===s&&(s=l(q,e.min)),e.isLog&&0>=s&&(s=null),p.total=p.stackTotal=u.total,p.percentage=u.total&&p.y/u.total*100,p.stackY=
n,u.setOffset(this.pointXOffset||0,this.barW||0));p.yBottom=t(s)?e.translate(s,0,1,0,1):null;h&&(n=this.modifyValue(n,p));p.plotY="number"===typeof n&&Infinity!==n?e.translate(n,0,1,0,1):v;p.clientX=m?c.translate(r,0,0,0,1):p.plotX;p.negative=p.y<(q||0);p.category=d&&d[p.x]!==v?d[p.x]:p.x}this.getSegments()},animate:function(a){var b=this.chart,c=b.renderer,d;d=this.options.animation;var e=this.clipBox||b.clipBox,f=b.inverted,g;d&&!Z(d)&&(d=Pa[this.type].animation);g=["_sharedClip",d.duration,d.easing,
e.height].join();a?(a=b[g],d=b[g+"m"],a||(b[g]=a=c.clipRect(y(e,{width:0})),b[g+"m"]=d=c.clipRect(-99,f?-b.plotLeft:-b.plotTop,99,f?b.chartWidth:b.chartHeight)),this.group.clip(a),this.markerGroup.clip(d),this.sharedClipKey=g):((a=b[g])&&a.animate({width:b.plotSizeX},d),b[g+"m"]&&b[g+"m"].animate({width:b.plotSizeX+99},d),this.animate=null)},afterAnimate:function(){var a=this.chart,b=this.sharedClipKey,c=this.group,d=this.clipBox;c&&!1!==this.options.clip&&(b&&d||c.clip(d?a.renderer.clipRect(d):a.clipRect),
this.markerGroup.clip());M(this,"afterAnimate");setTimeout(function(){b&&a[b]&&(d||(a[b]=a[b].destroy()),a[b+"m"]&&(a[b+"m"]=a[b+"m"].destroy()))},100)},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,g,h,k,m,q,p=this.options.marker,r=this.pointAttr[""],n,s,t,u=this.markerGroup,w=l(p.enabled,!this.requireSorting||this.activePointCount<.5*this.xAxis.len/p.radius);if(!1!==p.enabled||this._hasPointMarkers)for(f=b.length;f--;)g=b[f],d=Q(g.plotX),e=g.plotY,q=g.graphic,n=g.marker||{},s=!!g.marker,
a=w&&n.enabled===v||n.enabled,t=c.isInsidePlot(z(d),e,c.inverted),a&&e!==v&&!isNaN(e)&&null!==g.y?(a=g.pointAttr[g.selected?"select":""]||r,h=a.r,k=l(n.symbol,this.symbol),m=0===k.indexOf("url"),q?q[t?"show":"hide"](!0).animate(y({x:d-h,y:e-h},q.symbolName?{width:2*h,height:2*h}:{})):t&&(0<h||m)&&(g.graphic=c.renderer.symbol(k,d-h,e-h,2*h,2*h,s?n:p).attr(a).add(u))):q&&(g.graphic=q.destroy())},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={};a=a||{};b=b||{};c=c||{};d=d||{};
for(f in e)g=e[f],h[f]=l(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=a.options,c=Pa[a.type].marker?b.marker:b,d=c.states,e=d.hover,f,g=a.color;f={stroke:g,fill:g};var h=a.points||[],k,m=[],l,p=a.pointAttrToOptions;l=a.hasPointSpecificOptions;var r=b.negativeColor,n=c.lineColor,u=c.fillColor;k=b.turboThreshold;var v;b.marker?(e.radius=e.radius||c.radius+e.radiusPlus,e.lineWidth=e.lineWidth||c.lineWidth+e.lineWidthPlus):e.color=e.color||sa(e.color||g).brighten(e.brightness).get();
m[""]=a.convertAttribs(c,f);s(["hover","select"],function(b){m[b]=a.convertAttribs(d[b],m[""])});a.pointAttr=m;g=h.length;if(!k||g<k||l)for(;g--;){k=h[g];(c=k.options&&k.options.marker||k.options)&&!1===c.enabled&&(c.radius=0);k.negative&&r&&(k.color=k.fillColor=r);l=b.colorByPoint||k.color;if(k.options)for(v in p)t(c[p[v]])&&(l=!0);l?(c=c||{},l=[],d=c.states||{},f=d.hover=d.hover||{},b.marker||(f.color=f.color||!k.options.color&&e.color||sa(k.color).brighten(f.brightness||e.brightness).get()),f=
{color:k.color},u||(f.fillColor=k.color),n||(f.lineColor=k.color),l[""]=a.convertAttribs(y(f,c),m[""]),l.hover=a.convertAttribs(d.hover,m.hover,l[""]),l.select=a.convertAttribs(d.select,m.select,l[""])):l=m;k.pointAttr=l}},destroy:function(){var a=this,b=a.chart,c=/AppleWebKit\/533/.test(ha),d,e,f=a.data||[],g,h,k;M(a,"destroy");S(a);s(a.axisTypes||[],function(b){if(k=a[b])ma(k.series,a),k.isDirty=k.forceRedraw=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(e=f.length;e--;)(g=f[e])&&g.destroy&&
g.destroy();a.points=null;clearTimeout(a.animationTimeout);s("area graph dataLabelsGroup group markerGroup tracker graphNeg areaNeg posClip negClip".split(" "),function(b){a[b]&&(d=c&&"group"===b?"hide":"destroy",a[b][d]())});b.hoverSeries===a&&(b.hoverSeries=null);ma(b.series,a);for(h in a)delete a[h]},getSegmentPath:function(a){var b=this,c=[],d=b.options.step;s(a,function(e,f){var g=e.plotX,h=e.plotY,k;b.getPointSpline?c.push.apply(c,b.getPointSpline(a,e,f)):(c.push(f?"L":"M"),d&&f&&(k=a[f-1],
"right"===d?c.push(k.plotX,h):"center"===d?c.push((k.plotX+g)/2,k.plotY,(k.plotX+g)/2,h):c.push(g,k.plotY)),c.push(e.plotX,e.plotY))});return c},getGraphPath:function(){var a=this,b=[],c,d=[];s(a.segments,function(e){c=a.getSegmentPath(e);1<e.length?b=b.concat(c):d.push(e[0])});a.singlePoints=d;return a.graphPath=b},drawGraph:function(){var a=this,b=this.options,c=[["graph",b.lineColor||this.color]],d=b.lineWidth,e=b.dashStyle,f="square"!==b.linecap,g=this.getGraphPath(),h=b.negativeColor;h&&c.push(["graphNeg",
h]);s(c,function(c,h){var l=c[0],p=a[l];p?(Na(p),p.animate({d:g})):d&&g.length&&(p={stroke:c[1],"stroke-width":d,fill:"none",zIndex:1},e?p.dashstyle=e:f&&(p["stroke-linecap"]=p["stroke-linejoin"]="round"),a[l]=a.chart.renderer.path(g).attr(p).add(a.group).shadow(!h&&b.shadow))})},clipNeg:function(){var a=this.options,b=this.chart,c=b.renderer,d=a.negativeColor||a.negativeFillColor,e,f=this.graph,g=this.area,h=this.posClip,k=this.negClip;e=b.chartWidth;var l=b.chartHeight,q=u(e,l),p=this.yAxis;d&&
(f||g)&&(d=z(p.toPixels(a.threshold||0,!0)),0>d&&(q-=d),a={x:0,y:0,width:q,height:d},q={x:0,y:d,width:q,height:q},b.inverted&&(a.height=q.y=b.plotWidth-d,c.isVML&&(a={x:b.plotWidth-d-b.plotLeft,y:0,width:e,height:l},q={x:d+b.plotLeft-e,y:0,width:b.plotLeft+d,height:e})),p.reversed?(b=q,e=a):(b=a,e=q),h?(h.animate(b),k.animate(e)):(this.posClip=h=c.clipRect(b),this.negClip=k=c.clipRect(e),f&&this.graphNeg&&(f.clip(h),this.graphNeg.clip(k)),g&&(g.clip(h),this.areaNeg.clip(k))))},invertGroups:function(){function a(){var a=
{width:b.yAxis.len,height:b.xAxis.len};s(["group","markerGroup"],function(c){b[c]&&b[c].attr(a).invert()})}var b=this,c=b.chart;b.xAxis&&(L(c,"resize",a),L(b,"destroy",function(){S(c,"resize",a)}),a(),b.invertGroups=a)},plotGroup:function(a,b,c,d,e){var f=this[a],g=!f;g&&(this[a]=f=this.chart.renderer.g(b).attr({visibility:c,zIndex:d||.1}).add(e));f[g?"attr":"animate"](this.getPlotBox());return f},getPlotBox:function(){var a=this.chart,b=this.xAxis,c=this.yAxis;a.inverted&&(b=c,c=this.xAxis);return{translateX:b?
b.left:a.plotLeft,translateY:c?c.top:a.plotTop,scaleX:1,scaleY:1}},render:function(){var a=this,b=a.chart,c,d=a.options,e=(c=d.animation)&&!!a.animate&&b.renderer.isSVG&&l(c.duration,500)||0,f=a.visible?"visible":"hidden",g=d.zIndex,h=a.hasRendered,k=b.seriesGroup;c=a.plotGroup("group","series",f,g,k);a.markerGroup=a.plotGroup("markerGroup","markers",f,g,k);e&&a.animate(!0);a.getAttribs();c.inverted=a.isCartesian?b.inverted:!1;a.drawGraph&&(a.drawGraph(),a.clipNeg());s(a.points,function(a){a.redraw&&
a.redraw()});a.drawDataLabels&&a.drawDataLabels();a.visible&&a.drawPoints();a.drawTracker&&!1!==a.options.enableMouseTracking&&a.drawTracker();b.inverted&&a.invertGroups();!1===d.clip||a.sharedClipKey||h||c.clip(b.clipRect);e&&a.animate();h||(e?a.animationTimeout=setTimeout(function(){a.afterAnimate()},e):a.afterAnimate());a.isDirty=a.isDirtyData=!1;a.hasRendered=!0},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.group,d=this.xAxis,e=this.yAxis;c&&(a.inverted&&c.attr({width:a.plotWidth,
height:a.plotHeight}),c.animate({translateX:l(d&&d.left,a.plotLeft),translateY:l(e&&e.top,a.plotTop)}));this.translate();this.setTooltipPoints&&this.setTooltipPoints(!0);this.render();b&&M(this,"updatedData")}};var vb=Ta(Sa);ra.line=vb;y(V,{Axis:Aa,Chart:Ka,Color:sa,Point:Ga,Tick:ia,Renderer:ta,Series:Sa,SVGElement:K,SVGRenderer:ta,arrayMin:wa,arrayMax:pa,charts:ca,dateFormat:va,format:ua,pathAnim:Ma,getOptions:function(){return I},hasBidiBug:ob,isTouchDevice:eb,numberFormat:ba,seriesTypes:ra,setOptions:function(a){I=
D(!0,I,a);Ua();return I},addEvent:L,removeEvent:S,createElement:oa,discardElement:ya,css:O,each:s,extend:y,map:ib,merge:D,pick:l,splat:na,extendClass:Ta,pInt:B,wrap:Ia,svg:P,canvas:Y,vml:!P&&!Y,product:"Highcharts 4.0.4",version:"/Highstock 2.0.4"})})(); 
